Repository School-of-Company/Bitgouel-Frontend, pull requests merged in 2023-12, with the labels that each got.

#71 디자인 Typo 변경사항 적용
  packages/inside/src/PageContainer/Club/ActivityCreatePage/style.ts
  packages/inside/src/PageContainer/Club/ActivityDetailPage/index.tsx
  packages/inside/src/PageContainer/Club/ActivityDetailPage/style.ts
  packages/inside/src/PageContainer/Club/ActivityListPage/style.ts
  packages/inside/src/PageContainer/Club/ActivityModifyPage/style.ts
  packages/inside/src/PageContainer/Lecture/LectureDetailPage/style.ts
  packages/inside/src/PageContainer/Lecture/LecturePage/style.ts
  packages/inside/src/modals/LectureApplyModal/style.ts
  packages/outside/src/PageContainer/Club/ActivityCreatePage/style.ts
  packages/outside/src/PageContainer/Club/ActivityDetailPage/style.ts
  packages/outside/src/PageContainer/Club/ActivityListPage/style.ts
  packages/outside/src/PageContainer/Lecture/LectureCreatePage/index.tsx
  packages/outside/src/PageContainer/Lecture/LectureCreatePage/style.ts
  packages/outside/src/PageContainer/Lecture/LectureDetailPage/style.ts
  packages/outside/src/PageContainer/Lecture/LecturePage/style.ts
  shared/common/src/assets/png/agencySymbols/agency1.png
  shared/common/src/assets/png/agencySymbols/agency2.png
  shared/common/src/assets/png/agencySymbols/agency3.png
  shared/common/src/assets/png/agencySymbols/agency4.png
  shared/common/src/assets/png/clubListBanner1.png
  shared/common/src/assets/png/gwangjuLogo.png
  shared/common/src/assets/png/officeEducation.png
  shared/common/src/assets/png/schoolSymbols/JEONNAM_TECHNICAL_HIGH_SCHOOL.png
  shared/common/src/components/ActivityItem/style.ts
  shared/common/src/components/Header/style.ts
  shared/common/src/components/LectureItem/style.ts
  shared/common/src/components/SchoolIntro/style.ts
  shared/common/src/components/Sequence/style.ts
  shared/common/src/components/ValueInput/style.ts
  shared/common/src/components/index.ts
  shared/common/src/modals/ApproveModal/style.ts
  shared/common/src/modals/CreateModal/style.ts
  shared/common/src/modals/LectureTypeModal/style.ts
  shared/common/src/modals/SelectCalendarModal/style.ts
  shared/common/src/modals/SelectScoreModal/style.ts
  shared/common/src/pages/club/detail/style.ts
  shared/common/src/pages/club/student/style.ts
  shared/common/src/pages/club/style.ts
  shared/common/src/pages/home/index.tsx
  shared/common/src/pages/home/style.ts
  shared/common/src/pages/login/style.ts
  shared/common/src/pages/my/style.ts
  shared/common/src/pages/notice/index.tsx
  shared/common/src/pages/notice/style.ts
  shared/common/src/pages/signUp/Pagination/Page3/style.ts
  shared/common/src/pages/signUp/Pagination/SignUpButtonContainer/style.ts
  shared/common/src/pages/signUp/Pagination/SignUpScrollContainer/style.ts
  shared/common/src/pages/signUp/Pagination/SignUpSuccess/style.ts
  shared/common/src/pages/signUp/style.ts
  shared/common/src/styles/theme.ts
Labels: ⚙ Setting

#73 [Common] 메인 페이지 제작
  shared/common/src/assets/png/Gwangju.png
  shared/common/src/assets/png/OfficeGwangju.png
  shared/common/src/assets/png/gwangjuLogo.png
  shared/common/src/assets/png/officeEducation.png
  shared/common/src/pages/home/index.tsx
  shared/common/src/pages/home/style.ts
  shared/common/src/styles/globals.css
Labels: 🎨 Publishing

#74 [Common] 핵심 분야 및 참여 기업 소개 목록 페이지네이션
  pnpm-lock.yaml
  shared/common/package.json
  shared/common/src/assets/png/listBanner1.png
  shared/common/src/assets/png/listBanner2.png
  shared/common/src/assets/png/listBanner3.png
  shared/common/src/assets/png/listBanner4.png
  shared/common/src/assets/png/listBanner5.png
  shared/common/src/components/ClubListContents/ClubListContents1/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents1/style.ts
  shared/common/src/components/ClubListContents/ClubListContents2/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents2/style.ts
  shared/common/src/components/ClubListContents/ClubListContents3/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents3/style.ts
  shared/common/src/components/ClubListContents/ClubListContents4/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents4/style.ts
  shared/common/src/components/ClubListContents/ClubListContents5/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents5/style.ts
  shared/common/src/components/ClubListContents/index.ts
  shared/common/src/components/ClubListSlider/index.tsx
  shared/common/src/components/ClubListSlider/style.ts
  shared/common/src/components/CompanyListContents/CompanyListContents1/index.tsx
  shared/common/src/components/CompanyListContents/CompanyListContents1/style.ts
  shared/common/src/components/CompanyListContents/CompanyListContents2/index.tsx
  shared/common/src/components/CompanyListContents/CompanyListContents2/style.ts
  shared/common/src/components/CompanyListContents/CompanyListContents3/index.tsx
  shared/common/src/components/CompanyListContents/CompanyListContents3/style.ts
  shared/common/src/components/CompanyListContents/CompanyListContents4/index.tsx
  shared/common/src/components/CompanyListContents/CompanyListContents4/style.ts
  shared/common/src/components/CompanyListContents/CompanyListContents5/index.tsx
  shared/common/src/components/CompanyListContents/CompanyListContents5/style.ts
  shared/common/src/components/CompanyListContents/index.ts
  shared/common/src/components/CompanyListSlider/index.tsx
  shared/common/src/components/CompanyListSlider/style.ts
  shared/common/src/components/index.ts
  shared/common/src/pages/home/index.tsx
  shared/common/src/pages/home/style.ts
  shared/common/src/styles/theme.ts
Labels: 🎨 Publishing

#75 [Common] 학교 목록 map함수 key props 추가
  shared/common/src/components/SchoolIntro/index.tsx
Labels: ⚡️ Simple

#77 [Common]폰트 설정
  packages/outside/src/styles/font.css
Labels: ⚙ Setting

#78 [Common] 시퀀스의 이동 onClick 및 애니메이션 추가
  shared/common/src/components/Header/index.tsx
  shared/common/src/components/Sequence/index.tsx
  shared/common/src/pages/home/index.tsx
  shared/common/src/pages/home/style.ts
Labels: 🎨 Publishing

#79 [Common] 메인 페이지 리팩토링
  packages/inside/src/app/favicon.ico
  packages/inside/src/app/layout.tsx
  packages/outside/src/app/favicon.ico
  packages/outside/src/app/layout.tsx
  shared/common/src/components/ClubListContents/ClubListContents1/style.ts
  shared/common/src/components/ClubListContents/ClubListContents2/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents2/style.ts
  shared/common/src/components/ClubListContents/ClubListContents3/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents3/style.ts
  shared/common/src/components/ClubListContents/ClubListContents4/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents4/style.ts
  shared/common/src/components/ClubListContents/ClubListContents5/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents5/style.ts
  shared/common/src/components/ClubListSlider/style.ts
  shared/common/src/components/CompanyListContents/CompanyListContents1/index.tsx
  shared/common/src/components/CompanyListContents/CompanyListContents2/index.tsx
  shared/common/src/components/CompanyListContents/CompanyListContents2/style.ts
  shared/common/src/components/CompanyListContents/CompanyListContents3/index.tsx
  shared/common/src/components/CompanyListContents/CompanyListContents3/style.ts
  shared/common/src/components/CompanyListContents/CompanyListContents4/index.tsx
  shared/common/src/components/CompanyListContents/CompanyListContents4/style.ts
  shared/common/src/components/CompanyListContents/CompanyListContents5/index.tsx
  shared/common/src/components/CompanyListContents/CompanyListContents5/style.ts
  shared/common/src/components/CompanyListContents/style.ts
  shared/common/src/components/Sequence/style.ts
  shared/common/src/components/Sliders/ClubListSlider/index.tsx
  shared/common/src/components/Sliders/CompanyListSlider/index.tsx
  shared/common/src/components/Sliders/index.ts
  shared/common/src/components/Sliders/style.ts
  shared/common/src/components/index.ts
  shared/common/src/pages/home/index.tsx
  shared/common/src/pages/home/style.ts
Labels: ♻️ Refactor, 🎨 Publishing

#80 🔀 Deploy
  packages/inside/src/app/favicon.ico
  packages/inside/src/app/layout.tsx
  packages/outside/src/app/favicon.ico
  packages/outside/src/app/layout.tsx
  packages/outside/src/styles/font.css
  shared/common/src/components/ClubListContents/ClubListContents1/style.ts
  shared/common/src/components/ClubListContents/ClubListContents2/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents2/style.ts
  shared/common/src/components/ClubListContents/ClubListContents3/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents3/style.ts
  shared/common/src/components/ClubListContents/ClubListContents4/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents4/style.ts
  shared/common/src/components/ClubListContents/ClubListContents5/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents5/style.ts
  shared/common/src/components/ClubListSlider/style.ts
  shared/common/src/components/CompanyListContents/CompanyListContents1/index.tsx
  shared/common/src/components/CompanyListContents/CompanyListContents2/index.tsx
  shared/common/src/components/CompanyListContents/CompanyListContents2/style.ts
  shared/common/src/components/CompanyListContents/CompanyListContents3/index.tsx
  shared/common/src/components/CompanyListContents/CompanyListContents3/style.ts
  shared/common/src/components/CompanyListContents/CompanyListContents4/index.tsx
  shared/common/src/components/CompanyListContents/CompanyListContents4/style.ts
  shared/common/src/components/CompanyListContents/CompanyListContents5/index.tsx
  shared/common/src/components/CompanyListContents/CompanyListContents5/style.ts
  shared/common/src/components/CompanyListContents/style.ts
  shared/common/src/components/Header/index.tsx
  shared/common/src/components/SchoolIntro/index.tsx
  shared/common/src/components/SchoolIntro/style.ts
  shared/common/src/components/Sequence/index.tsx
  shared/common/src/components/Sequence/style.ts
  shared/common/src/components/Sliders/ClubListSlider/index.tsx
  shared/common/src/components/Sliders/CompanyListSlider/index.tsx
  shared/common/src/components/Sliders/index.ts
  shared/common/src/components/Sliders/style.ts
  shared/common/src/components/index.ts
  shared/common/src/pages/home/style.ts
  shared/common/src/styles/globals.css
Labels: 🌏 Deploy

#81 🔀 Deploy
  shared/common/src/components/SchoolIntro/index.tsx
  shared/common/src/components/SchoolIntro/style.ts
  shared/common/src/pages/home/style.ts
  shared/common/src/styles/globals.css
Labels: 🌏 Deploy

#83 [Common] 회원가입 인증 글자 색깔 수정
  shared/common/src/pages/signUp/Pagination/Page3/index.tsx
Labels: ⚡️ Simple, 🎨 Publishing

#91 [Common] 시퀀스 및 홈 디자인 수정
  shared/common/src/components/Sequence/index.tsx
  shared/common/src/pages/home/index.tsx
Labels: 🎨 Publishing

#96 [Common] 메인 슬라이드 style 수정
  shared/common/src/assets/svg/Arrow.tsx
  shared/common/src/assets/svg/CanView.tsx
  shared/common/src/assets/svg/Card.tsx
  shared/common/src/assets/svg/Check.tsx
  shared/common/src/assets/svg/Chevron.tsx
  shared/common/src/assets/svg/Circle.tsx
  shared/common/src/assets/svg/Filter.tsx
  shared/common/src/assets/svg/Link.tsx
  shared/common/src/assets/svg/MegaPhone.tsx
  shared/common/src/assets/svg/Message.tsx
  shared/common/src/assets/svg/NotView.tsx
  shared/common/src/assets/svg/Pen.tsx
  shared/common/src/assets/svg/People.tsx
  shared/common/src/assets/svg/Person.tsx
  shared/common/src/assets/svg/PersonOut.tsx
  shared/common/src/assets/svg/Plus.tsx
  shared/common/src/assets/svg/Question.tsx
  shared/common/src/assets/svg/SettingCircle.tsx
  shared/common/src/assets/svg/SettingOut.tsx
  shared/common/src/assets/svg/SlideLeftArrow.tsx
  shared/common/src/assets/svg/SlideRightArrow.tsx
  shared/common/src/assets/svg/Surprise.tsx
  shared/common/src/assets/svg/TrashCan.tsx
  shared/common/src/assets/svg/XIcon.tsx
  shared/common/src/assets/svg/index.ts
  shared/common/src/components/ClubListContents/ClubListContents1/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents1/style.ts
  shared/common/src/components/ClubListContents/ClubListContents2/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents3/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents3/style.ts
  shared/common/src/components/ClubListContents/ClubListContents4/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents4/style.ts
  shared/common/src/components/ClubListContents/ClubListContents5/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents5/style.ts
  shared/common/src/components/ClubListContents/style.ts
  shared/common/src/components/CompanyListContents/style.ts
  shared/common/src/components/Sequence/index.tsx
  shared/common/src/components/Sliders/ClubListSlider/index.tsx
  shared/common/src/components/Sliders/CompanyListSlider/index.tsx
  shared/common/src/components/Sliders/style.ts
  shared/common/src/pages/home/index.tsx
  shared/common/src/pages/home/style.ts
  shared/common/src/pages/post/index.tsx
Labels: ⚡️ Simple, 🎨 Publishing

#98 [Common] 회원가입 인증 로직 삭제
  shared/common/src/pages/login/index.tsx
  shared/common/src/pages/signUp/Pagination/Page3/index.tsx
  shared/common/src/pages/signUp/Pagination/Page3/style.ts
Labels: ♻️ Refactor, ⚡️performance

#99 [Common] 재발급 구현
  shared/api/common/src/libs/api/TokenManager.ts
  shared/api/common/src/libs/api/instance.ts
Labels: ⚡️performance, ✨ Feature

#102 [Common] 입학년도 입력 Scroll로 변경
  shared/common/src/constants/signUpObject.ts
  shared/common/src/pages/signUp/Pagination/Page2/index.tsx
  shared/common/src/pages/signUp/Pagination/SignUpButtonContainer/index.tsx
  shared/common/src/pages/signUp/Pagination/SignUpScrollContainer/index.tsx
  shared/common/src/pages/signUp/Pagination/SignUpScrollContainer/style.ts
Labels: ⚡️performance

#104 [Common] 학생정보 페이지 자격증 임시 수정 기능 추가
  shared/common/src/pages/club/student/index.tsx
  shared/common/src/pages/club/student/style.ts
Labels: ✨ Feature, 🎨 Publishing
