Repository School-of-Company/Bitgouel-Frontend, pull requests merged in 2023-11, with the labels that each got.

#5 [Common] SignUpSuccess
  shared/common/src/components/Login/index.tsx
  shared/common/src/components/Login/style.ts
  shared/common/src/components/SignUpSuccess/index.stories.tsx
  shared/common/src/components/SignUpSuccess/index.tsx
  shared/common/src/components/SignUpSuccess/style.ts
  shared/common/src/components/ValueInput/index.tsx
  shared/common/src/components/ValueInput/style.ts
Labels: 🎨 Publishing

#8 [Common] SignUp Requirements
  packages/inside/src/pages/auth/login/index.tsx
  shared/common/src/atoms/index.ts
  shared/common/src/components/Login/index.tsx
  shared/common/src/components/SignUp/Pagination/Page1/index.tsx
  shared/common/src/components/SignUp/Pagination/Page1/style.ts
  shared/common/src/components/SignUp/Pagination/Page2/index.tsx
  shared/common/src/components/SignUp/Pagination/Page3/index.tsx
  shared/common/src/components/SignUp/Pagination/Page3/style.ts
  shared/common/src/components/SignUp/Pagination/SignUpButtonContainer/index.tsx
  shared/common/src/components/SignUp/Pagination/SignUpButtonContainer/style.ts
  shared/common/src/components/SignUp/Pagination/SignUpScrollContainer/index.tsx
  shared/common/src/components/SignUp/Pagination/SignUpScrollContainer/style.ts
  shared/common/src/components/SignUp/index.tsx
  shared/common/src/components/SignUp/style.ts
  shared/common/src/components/ValueInput/index.tsx
  shared/common/src/components/ValueInput/style.ts
  shared/common/src/constants/signUpObject.ts
Labels: ⚡️ Simple, 🎨 Publishing

#9 [Common] 이미지 임포트 해결
  shared/common/src/assets/png/simbol.png
  shared/common/src/components/Header/index.tsx
  shared/common/src/image.d.ts
Labels: ♻️ Refactor

#12 [Common] Club Page 추가
  packages/inside/src/pages/main/club/index.tsx
  packages/outside/src/pages/main/club/index.tsx
  shared/common/src/pages/club/index.tsx
  shared/common/src/pages/club/style.ts
  shared/common/src/pages/home/index.tsx
  shared/common/src/pages/home/style.ts
  shared/common/src/pages/index.ts
  shared/common/src/pages/lecture/index.tsx
  shared/common/src/pages/lecture/style.ts
Labels: 🎨 Publishing

#13 [Common] Modal 세팅
  packages/inside/src/pages/_app.tsx
  packages/inside/src/pages/_document.tsx
  packages/outside/src/pages/_app.tsx
  packages/outside/src/pages/_document.tsx
  pnpm-lock.yaml
  shared/common/package.json
  shared/common/src/atoms/index.ts
  shared/common/src/hooks/index.ts
  shared/common/src/hooks/useModal.tsx
  shared/common/src/index.ts
  shared/common/src/modals/.gitkeep
  shared/common/src/portal/index.tsx
Labels: ✨ Feature

#16 [Common] Arrow svg 디자인 변경
  shared/common/src/assets/svg/Arrow.tsx
  shared/common/src/pages/home/index.tsx
  shared/common/src/pages/home/style.ts
Labels: 🎨 Publishing

#17 [Common] RecoilRoot 위치 수정
  packages/inside/src/pages/_app.tsx
  packages/outside/src/pages/_app.tsx
  shared/common/src/layouts/GlobalLayout.tsx
Labels: ⚙ Setting, ⚡️ Simple

#18 [Common] 로그인 API 연결
  packages/inside/.env
  packages/inside/next.config.js
  packages/outside/next.config.js
  pnpm-lock.yaml
  shared/api/common/index.ts
  shared/api/common/src/hooks/auth/index.ts
  shared/api/common/src/hooks/auth/usePatchAccessToken.ts
  shared/api/common/src/hooks/auth/usePostLogin.ts
  shared/api/common/src/hooks/index.ts
  shared/api/common/src/index.ts
  shared/api/common/src/libs/api/TokenManager.ts
  shared/api/common/src/libs/api/index.ts
  shared/api/common/src/libs/api/instance.ts
  shared/api/common/src/libs/api/method.ts
  shared/api/common/src/libs/index.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/api/common/src/libs/token.ts
  shared/api/common/src/libs/urlController.ts
  shared/api/index.ts
  shared/api/package.json
  shared/api/tsconfig.json
  shared/common/src/components/Login/index.tsx
  shared/common/src/components/SignUp/Pagination/Page3/index.tsx
  shared/common/src/layouts/GlobalLayout.tsx
  shared/common/tsconfig.json
  shared/types/index.ts
  shared/types/package.json
  shared/types/src/index.ts
  shared/types/src/tokenResponseType.ts
Labels: ✨ Feature

#22 [Common] header 제작 완료
  shared/api/common/src/libs/token.ts
  shared/common/src/assets/svg/Filter.tsx
  shared/common/src/assets/svg/MegaPhone.tsx
  shared/common/src/assets/svg/Message.tsx
  shared/common/src/assets/svg/Plus.tsx
  shared/common/src/assets/svg/Question.tsx
  shared/common/src/components/Header/index.tsx
  shared/common/src/components/Header/style.ts
  shared/common/src/pages/home/index.tsx
  shared/common/src/pages/lecture/index.tsx
  shared/common/src/pages/lecture/style.ts
  shared/common/src/pages/notice/style.ts
  shared/common/src/styles/theme.ts
Labels: 🎨 Publishing

#23 export 및 import error 해결
  packages/inside/src/pages/auth/login/index.tsx
  packages/inside/src/pages/auth/signUp/index.tsx
  packages/inside/src/pages/index.tsx
  packages/inside/src/pages/main/club/index.tsx
  packages/inside/src/pages/main/home/index.tsx
  packages/inside/src/pages/main/lecture/index.tsx
  packages/inside/src/pages/main/notice/index.tsx
  shared/api/common/src/hooks/auth/usePostBbozzakSignUp.ts
  shared/api/common/src/hooks/auth/usePostCompanyInstructorSignUp.ts
  shared/api/common/src/hooks/auth/usePostGovernmentSignUp.ts
  shared/api/common/src/hooks/auth/usePostProfessorSignUp.ts
  shared/api/common/src/hooks/auth/usePostStudentSignUp.ts
  shared/api/common/src/hooks/auth/usePostTeacherSignUp.ts
  shared/api/common/src/libs/api/instance.ts
  shared/common/index.ts
  shared/common/package.json
  shared/common/src/components/Sequence/index.tsx
  shared/common/src/components/index.ts
  shared/common/src/index.ts
  shared/common/src/pages/home/index.tsx
  shared/common/src/pages/index.ts
  shared/common/src/pages/lecture/index.tsx
  shared/common/src/pages/login/index.stories.tsx
  shared/common/src/pages/login/index.tsx
  shared/common/src/pages/login/style.ts
  shared/common/src/pages/notice/index.tsx
  shared/common/src/pages/signUp/Pagination/Page1/index.tsx
  shared/common/src/pages/signUp/Pagination/Page1/style.ts
  shared/common/src/pages/signUp/Pagination/Page2/index.tsx
  shared/common/src/pages/signUp/Pagination/Page3/index.tsx
  shared/common/src/pages/signUp/Pagination/Page3/style.ts
  shared/common/src/pages/signUp/Pagination/SignUpButtonContainer/index.stories.tsx
  shared/common/src/pages/signUp/Pagination/SignUpButtonContainer/index.tsx
  shared/common/src/pages/signUp/Pagination/SignUpButtonContainer/style.ts
  shared/common/src/pages/signUp/Pagination/SignUpScrollContainer/index.tsx
  shared/common/src/pages/signUp/Pagination/SignUpScrollContainer/style.ts
  shared/common/src/pages/signUp/Pagination/SignUpSuccess/index.stories.tsx
  shared/common/src/pages/signUp/Pagination/SignUpSuccess/index.tsx
  shared/common/src/pages/signUp/Pagination/SignUpSuccess/style.ts
  shared/common/src/pages/signUp/index.stories.tsx
  shared/common/src/pages/signUp/index.tsx
  shared/common/src/pages/signUp/style.ts
Labels: 1️⃣ Priority: High

#25 [Common, Outside] 강의 페이지 제작
  packages/inside/src/pages/main/lecture/create/index.tsx
  packages/inside/src/pages/main/lecture/detail/index.tsx
  packages/outside/src/image.d.ts
  packages/outside/src/pages/auth/login/index.tsx
  packages/outside/src/pages/auth/signUp/index.tsx
  packages/outside/src/pages/index.tsx
  packages/outside/src/pages/main/club/index.tsx
  packages/outside/src/pages/main/home/index.tsx
  packages/outside/src/pages/main/lecture/create/index.tsx
  packages/outside/src/pages/main/lecture/create/style.ts
  packages/outside/src/pages/main/lecture/detail/index.tsx
  packages/outside/src/pages/main/lecture/index.tsx
  packages/outside/src/pages/main/notice/index.tsx
  packages/storybook/.storybook/main.js
  shared/common/src/assets/index.ts
  shared/common/src/assets/svg/Chevron.tsx
  shared/common/src/assets/svg/People.tsx
  shared/common/src/components/LectureItem/index.stories.tsx
  shared/common/src/components/LectureItem/index.tsx
  shared/common/src/components/LectureItem/style.ts
  shared/common/src/components/index.ts
  shared/common/src/constants/index.ts
  shared/common/src/constants/lectureObject.ts
  shared/common/src/pages/index.ts
  shared/common/src/pages/lecture/detail/index.tsx
  shared/common/src/pages/lecture/detail/style.ts
  shared/common/src/pages/lecture/index.tsx
  shared/common/src/pages/lecture/style.ts
  shared/common/tsconfig.json
Labels: 🎨 Publishing

#26 Inside 부분의 강의 생성 페이지 삭제
  packages/inside/src/pages/main/lecture/create/index.tsx
Labels: 2️⃣ Priority: Medium

#27 Type 에러와 theme import 오류를 픽스했습니다
  .nvmrc
  packages/inside/src/emotion.d.ts
  packages/inside/src/image.d.ts
  packages/inside/src/styles/index.ts
  packages/inside/src/styles/theme.ts
  packages/outside/src/emotion.d.ts
  packages/outside/src/pages/main/lecture/create/index.tsx
  packages/outside/src/styles/create/style.ts
  packages/outside/src/styles/index.ts
  packages/outside/src/styles/theme.ts
  shared/common/src/components/Header/index.tsx
  shared/common/tsconfig.json
Labels: 2️⃣ Priority: Medium

#28 [Common] 로그인 오류 입력 창 퍼블리싱
  shared/api/common/src/hooks/auth/usePostLogin.ts
  shared/common/src/components/ValueInput/index.tsx
  shared/common/src/components/ValueInput/style.ts
  shared/common/src/pages/login/index.tsx
  shared/common/src/pages/login/style.ts
Labels: ⚡️performance, 🎨 Publishing

#29 Ts-Patter 라이브러리 적용 및 코드 리팩토링
  pnpm-lock.yaml
  shared/common/package.json
  shared/common/src/assets/png/symbol1.png
  shared/common/src/assets/png/symbol2.png
  shared/common/src/components/Header/index.tsx
  shared/common/src/components/Header/style.ts
  shared/common/src/pages/club/index.tsx
  shared/common/src/pages/club/style.ts
  shared/common/src/pages/home/index.tsx
  shared/common/src/pages/home/style.ts
  shared/common/src/pages/lecture/detail/index.tsx
  shared/common/src/pages/lecture/detail/style.ts
  shared/common/src/pages/lecture/index.tsx
  shared/common/src/pages/lecture/style.ts
  shared/common/src/pages/notice/index.tsx
  shared/common/src/pages/notice/style.ts
  shared/common/src/pages/signUp/Pagination/Page1/index.tsx
  shared/common/src/pages/signUp/Pagination/SignUpButtonContainer/index.tsx
  shared/common/src/pages/signUp/Pagination/SignUpScrollContainer/style.ts
  shared/common/src/pages/signUp/index.tsx
Labels: ♻️ Refactor, ⚙ Setting, ⚡️performance

#31 [Outside] 강의 개설 신청 useState 추가
  packages/outside/src/pages/main/lecture/create/index.tsx
  packages/outside/src/styles/create/style.ts
Labels: ⚙ Setting, ⚡️ Simple

#32 [Common, Outside] 강의 필터 모달, 캘린더 모달 퍼블리싱
  packages/inside/next.config.js
  packages/inside/src/styles/theme.ts
  packages/outside/next.config.js
  packages/outside/package.json
  packages/outside/src/modals/SelectCalendarModal/index.tsx
  packages/outside/src/modals/SelectCalendarModal/style.ts
  packages/outside/src/modals/SelectScoreModal/index.tsx
  packages/outside/src/modals/SelectScoreModal/style.ts
  packages/outside/src/modals/index.ts
  packages/outside/src/pages/main/lecture/create/index.tsx
  packages/outside/src/styles/create/style.ts
  packages/outside/src/styles/theme.ts
  pnpm-lock.yaml
  shared/common/src/atoms/index.ts
  shared/common/src/components/Header/index.tsx
  shared/common/src/components/Header/style.ts
  shared/common/src/components/LectureItem/index.tsx
  shared/common/src/constants/lectureObject.ts
  shared/common/src/index.ts
  shared/common/src/modals/.gitkeep
  shared/common/src/modals/LectureTypeModal/index.tsx
  shared/common/src/modals/LectureTypeModal/style.ts
  shared/common/src/modals/index.ts
  shared/common/src/pages/lecture/index.tsx
  shared/common/src/pages/lecture/style.ts
  shared/common/src/pages/login/index.tsx
  shared/common/src/styles/theme.ts
Labels: ✨ Feature, 🎨 Publishing

#34 [Common, Outside] lecture, modal 반응형 추가
  packages/outside/src/modals/SelectCalendarModal/style.ts
  packages/outside/src/modals/SelectScoreModal/style.ts
  packages/outside/src/styles/create/style.ts
  shared/common/src/components/Header/index.tsx
  shared/common/src/modals/LectureTypeModal/style.ts
  shared/common/src/pages/lecture/detail/style.ts
Labels: 🎨 Publishing

#33 [Common] Lecture QuerySetting
  shared/api/common/src/hooks/index.ts
  shared/api/common/src/hooks/lecture/index.ts
  shared/api/common/src/hooks/lecture/useDeleteRejectLecture.ts
  shared/api/common/src/hooks/lecture/useGetDetailLecture.ts
  shared/api/common/src/hooks/lecture/useGetLectureList.ts
  shared/api/common/src/hooks/lecture/usePatchApproveLecture.ts
  shared/api/common/src/hooks/lecture/usePostApplicationLecture.ts
  shared/api/common/src/hooks/lecture/usePostCreateLecture.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/api/common/src/libs/urlController.ts
Labels: ⚙ Setting

#35 [Common] 재발급 관련 변경 및 Query Devtools 설정
  shared/api/common/src/hooks/auth/index.ts
  shared/api/common/src/hooks/auth/useReissue.ts
  shared/api/common/src/libs/api/instance.ts
  shared/api/common/src/libs/queryKeys.ts
Labels: ⚡️ Simple

#36 [Inside, Outside] 강의 페이지 권한별 설정
  packages/inside/src/pages/_app.tsx
  packages/inside/src/pages/main/lecture/detail/index.tsx
  packages/inside/src/pages/main/lecture/index.tsx
  packages/inside/src/styles/lecture/detail/style.ts
  packages/inside/src/styles/lecture/style.ts
  packages/inside/src/styles/theme.ts
  packages/outside/src/pages/_app.tsx
  packages/outside/src/pages/main/lecture/create/index.tsx
  packages/outside/src/pages/main/lecture/detail/index.tsx
  packages/outside/src/pages/main/lecture/index.tsx
  packages/outside/src/styles/lecture/create/style.ts
  packages/outside/src/styles/lecture/detail/style.ts
  packages/outside/src/styles/lecture/style.ts
  packages/outside/src/styles/theme.ts
  shared/common/src/components/Header/index.tsx
  shared/common/src/components/Header/style.ts
  shared/common/src/components/LectureItem/index.tsx
  shared/common/src/components/LectureItem/style.ts
  shared/common/src/constants/lectureObject.ts
  shared/common/src/pages/club/index.tsx
  shared/common/src/pages/home/index.tsx
  shared/common/src/pages/index.ts
  shared/common/src/pages/lecture/detail/index.tsx
  shared/common/src/pages/lecture/index.tsx
  shared/common/src/pages/notice/index.tsx
  shared/common/src/pages/signUp/Pagination/Page1/index.tsx
  shared/common/src/styles/theme.ts
Labels: ♻️ Refactor, 🎨 Publishing

#37 [Inside, Outside] 강의 리스트 inside, outside View 차이 구현
  packages/inside/src/pages/main/lecture/index.tsx
  packages/outside/src/pages/main/lecture/index.tsx
  shared/common/src/components/Header/index.tsx
  shared/common/src/components/LectureItem/index.tsx
  shared/common/src/components/LectureItem/style.ts
Labels: ♻️ Refactor, 🎨 Publishing

#42 [Common] 마이페이지 생성에 따른 헤더 변경 및 코드 리팩토링
  shared/common/src/components/Header/index.tsx
  shared/common/src/components/Header/style.ts
Labels: ⚙ Setting, ⚡️performance

#43 [Common] Header 버튼 글자 상태 관리 오류 해결
  shared/api/common/src/hooks/lecture/useGetDetailLecture.ts
  shared/common/src/components/Header/index.tsx
  shared/common/src/pages/club/index.tsx
  shared/common/src/pages/club/style.ts
Labels: ♻️ Refactor, 🐞 Bug

#44 [Common] localStorage 대신 tokenManager로 변경
  shared/common/src/components/Header/index.tsx
Labels: ⚡️ Simple

#46 [Common] 강의 부분 useMutation 반환 타입 수정
  shared/api/common/src/hooks/lecture/useDeleteRejectLecture.ts
  shared/api/common/src/hooks/lecture/usePostApplicationLecture.ts
Labels: ⚡️ Simple

#52 [Inside, Outside] 학생활동 디자인 변경사항 업데이트
  packages/inside/src/PageContainer/Club/ActivityCreatePage/index.tsx
  packages/inside/src/PageContainer/Club/ActivityCreatePage/style.ts
  packages/inside/src/PageContainer/Club/ActivityDetailPage/index.tsx
  packages/inside/src/PageContainer/Club/ActivityDetailPage/style.ts
  packages/inside/src/PageContainer/Club/ActivityListPage/index.tsx
  packages/inside/src/PageContainer/Club/ActivityListPage/style.ts
  packages/inside/src/PageContainer/Club/ActivityModifyPage/index.tsx
  packages/inside/src/PageContainer/Club/ActivityModifyPage/style.ts
  packages/inside/src/app/main/club/student/activity/create/page.tsx
  packages/inside/src/app/main/club/student/activity/detail/modify/page.tsx
  packages/inside/src/app/main/club/student/activity/detail/page.tsx
  packages/inside/src/app/main/club/student/activity/page.tsx
  packages/outside/src/PageContainer/Club/ActivityCreatePage/index.tsx
  packages/outside/src/PageContainer/Club/ActivityCreatePage/style.ts
  packages/outside/src/PageContainer/Club/ActivityDetailPage/index.tsx
  packages/outside/src/PageContainer/Club/ActivityDetailPage/style.ts
  packages/outside/src/PageContainer/Club/ActivityListPage/index.tsx
  packages/outside/src/PageContainer/Club/ActivityListPage/style.ts
  packages/outside/src/app/main/club/student/activity/create/page.tsx
  packages/outside/src/app/main/club/student/activity/detail/page.tsx
  packages/outside/src/app/main/club/student/activity/page.tsx
  shared/common/src/components/ActivityItem/index.tsx
  shared/common/src/components/ActivityItem/style.ts
  shared/common/src/pages/index.ts
Labels: ⚙ Setting, 🎨 Publishing

#47 [Common] 반응형 및 pathname 리팩토링
  packages/outside/src/PageContainer/Lecture/LectureDetailPage/index.tsx
  packages/outside/src/PageContainer/Lecture/LectureDetailPage/style.ts
  shared/common/src/components/ActivityItem/index.tsx
  shared/common/src/components/Header/index.tsx
  shared/common/src/modals/LectureTypeModal/style.ts
  shared/common/src/pages/home/index.tsx
  shared/common/src/pages/home/style.ts
  shared/common/src/styles/globals.css
Labels: ♻️ Refactor, ⚡️ Simple

#55 [Common] activity QuerySettings <renew>
  pnpm-lock.yaml
  shared/api/common/src/hooks/activity/index.ts
  shared/api/common/src/hooks/activity/useDeleteActivityInformationRemove.ts
  shared/api/common/src/hooks/activity/useDeleteRejectActivity.ts
  shared/api/common/src/hooks/activity/useGetActivityDetail.ts
  shared/api/common/src/hooks/activity/useGetActivityInformationList.ts
  shared/api/common/src/hooks/activity/useGetActivityMyselfList.ts
  shared/api/common/src/hooks/activity/usePatchActivityApprove.ts
  shared/api/common/src/hooks/activity/usePatchActivityCorrection.ts
  shared/api/common/src/hooks/activity/usePostActivityInformation.ts
  shared/api/common/src/hooks/index.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/api/common/src/libs/urlController.ts
  shared/api/common/src/types/hooks/activity/ActivityListDetailTypes.ts
  shared/api/common/src/types/hooks/activity/ActivityListTypes.ts
  shared/api/common/src/types/libs/ActivityOptionsTypes.ts
  shared/api/common/src/types/libs/index.ts
Labels: ⚙ Setting, ✨ Feature

#51 [Common] 로그인 관련 오류 조절
  shared/api/common/src/hooks/auth/usePostLogin.ts
  shared/common/src/pages/login/index.tsx
  shared/common/src/pages/login/style.ts
Labels: ✨ Feature, 🎨 Publishing

#56 Revert "[Common] 로그인 관련 오류 조절"
  shared/api/common/src/hooks/auth/usePostLogin.ts
  shared/common/src/pages/login/index.tsx
  shared/common/src/pages/login/style.ts
Labels: 🐞 Bug

#57 [Common] 로그인 오류 핸들링
  shared/api/common/src/hooks/auth/usePostLogin.ts
  shared/common/src/pages/login/index.tsx
  shared/common/src/pages/login/style.ts
Labels: ⚡️performance, ✨ Feature

#61 [Inside, Outside] 강의 관련 API들의 오류 관리
  package.json
  packages/inside/src/PageContainer/Lecture/LecturePage/index.tsx
  packages/inside/src/PageContainer/Lecture/LecturePage/style.ts
  packages/outside/src/PageContainer/Lecture/LectureCreatePage/index.tsx
  packages/outside/src/PageContainer/Lecture/LectureDetailPage/index.tsx
  packages/outside/src/PageContainer/Lecture/LecturePage/index.tsx
  packages/outside/src/PageContainer/Lecture/LecturePage/style.ts
  packages/outside/src/modals/LectureCreateModal/index.tsx
  packages/outside/src/modals/LectureCreateNoticeModal/index.stories.tsx
  packages/outside/src/modals/LectureCreateNoticeModal/index.tsx
  packages/outside/src/modals/LectureCreateNoticeModal/style.ts
  packages/outside/src/modals/index.ts
  pnpm-lock.yaml
  shared/api/common/src/libs/queryKeys.ts
  shared/api/inside/src/hooks/lecture/usePostApplicationLecture.ts
  shared/api/outside/src/hooks/lecture/useDeleteRejectLecture.ts
  shared/api/outside/src/hooks/lecture/usePatchApproveLecture.ts
  shared/api/outside/src/hooks/lecture/usePostCreateLecture.ts
  shared/common/src/layouts/GlobalLayout.tsx
  shared/types/src/api/common/LectureListResponseTypes.ts
  shared/types/src/api/inside/LectureApplicationErrorTypes.ts
  shared/types/src/api/inside/index.ts
Labels: ⚙ Setting, ✨ Feature

#62 [Common] 강의 개설, 활동 추가 모달 공통화
  packages/inside/src/PageContainer/Club/ActivityCreatePage/index.tsx
  packages/inside/src/PageContainer/Club/ActivityDetailPage/index.tsx
  packages/inside/src/app/main/club/student/activity/[activityId]/modify/page.tsx
  packages/inside/src/app/main/club/student/activity/[activityId]/page.tsx
  packages/inside/src/app/main/club/student/activity/detail/page.tsx
  packages/outside/src/PageContainer/Club/ActivityCreatePage/index.tsx
  packages/outside/src/PageContainer/Club/ActivityDetailPage/index.tsx
  packages/outside/src/PageContainer/Lecture/LectureCreatePage/index.tsx
  packages/outside/src/PageContainer/Lecture/LectureDetailPage/index.tsx
  packages/outside/src/app/main/club/student/activity/[activityId]/page.tsx
  packages/outside/src/app/main/club/student/activity/detail/page.tsx
  packages/outside/src/modals/LectureCreateModal/index.stories.tsx
  packages/outside/src/modals/LectureCreateModal/index.tsx
  packages/outside/src/modals/index.ts
  shared/common/src/modals/ApproveModal/index.tsx
  shared/common/src/modals/CreateModal/index.stories.tsx
  shared/common/src/modals/CreateModal/index.tsx
  shared/common/src/modals/CreateModal/style.ts
  shared/common/src/modals/RejectModal/index.tsx
  shared/common/src/modals/index.ts
  shared/types/src/common/AppropriationModalProps.ts
  shared/types/src/common/CreateModalProps.ts
  shared/types/src/common/index.ts
  shared/types/src/index.ts
  shared/types/src/outside/LectureCreateModalProps.ts
  shared/types/src/outside/index.ts
Labels: ♻️ Refactor

#63 [Common] 마이페이지 제작
  packages/inside/src/app/main/my/page.tsx
  packages/outside/src/app/main/my/page.tsx
  shared/api/common/src/hooks/index.ts
  shared/api/common/src/hooks/my/index.ts
  shared/api/common/src/hooks/my/useGetMy.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/api/common/src/libs/urlController.ts
  shared/common/src/assets/png/clipBox.png
  shared/common/src/components/Header/index.tsx
  shared/common/src/pages/home/style.ts
  shared/common/src/pages/index.ts
  shared/common/src/pages/my/index.tsx
  shared/common/src/pages/my/style.ts
  shared/types/src/api/common/MyPageResponseTypes.ts
  shared/types/src/api/common/index.ts
Labels: ✨ Feature, 🎨 Publishing

#64 권한 가져오기
  shared/api/common/src/hooks/auth/usePostLogin.ts
  shared/common/src/atoms/index.ts
  shared/types/src/api/common/LoginResponseTypes.ts
Labels: ✨ Feature

#66 [Inside, Outside] 강의 개설 리팩토링 및 글자 변환 오브젝트들 수정
  packages/inside/src/PageContainer/Lecture/LectureDetailPage/index.tsx
  packages/outside/src/PageContainer/Lecture/LectureCreatePage/index.tsx
  packages/outside/src/PageContainer/Lecture/LectureDetailPage/index.tsx
Labels: ♻️ Refactor, ⚡️performance

#65 [Common] 마이페이지 로그아웃, 회원탈퇴 기능 구현
  shared/api/common/src/hooks/auth/index.ts
  shared/api/common/src/hooks/auth/useDeleteLogout.ts
  shared/api/common/src/hooks/auth/useDeleteWithDraw.ts
  shared/common/src/components/Header/index.tsx
  shared/common/src/constants/index.ts
  shared/common/src/constants/myObject.ts
  shared/common/src/pages/my/index.tsx
  shared/common/src/pages/my/style.ts
Labels: ✨ Feature

#67 [Common] 로그인 로딩 시 스타일 적용
  shared/common/src/pages/login/index.tsx
Labels: ✨ Feature

#68 Storybook 오류 해결 (parameter)
  packages/inside/src/PageContainer/Club/ActivityDetailPage/index.tsx
  packages/inside/src/PageContainer/Lecture/LecturePage/index.tsx
  packages/inside/src/app/layout.tsx
  packages/outside/src/PageContainer/Lecture/LecturePage/index.tsx
  packages/outside/src/app/layout.tsx
  packages/storybook/.storybook/main.js
  packages/storybook/.storybook/preview.js
  shared/common/src/components/ActivityItem/index.stories.tsx
  shared/common/src/components/ActivityItem/index.tsx
  shared/common/src/components/ActivityItem/style.ts
  shared/common/src/components/Header/index.stories.tsx
  shared/common/src/components/Header/index.tsx
  shared/common/src/components/LectureItem/index.stories.tsx
  shared/common/src/components/LectureItem/index.tsx
  shared/common/src/components/LectureItem/style.ts
  shared/common/src/components/Sequence/index.stories.tsx
  shared/common/src/components/ValueInput/index.stories.tsx
  shared/common/src/modals/ApproveModal/index.stories.tsx
  shared/common/src/modals/ApproveModal/index.tsx
  shared/common/src/modals/CreateModal/index.stories.tsx
  shared/common/src/modals/LectureTypeModal/index.stories.tsx
  shared/common/src/modals/RejectModal/index.stories.tsx
  shared/common/src/modals/SelectCalendarModal/index.stories.tsx
  shared/common/src/modals/SelectScoreModal/index.stories.tsx
  shared/common/src/pages/login/index.stories.tsx
  shared/common/src/pages/signUp/index.stories.tsx
  shared/types/src/common/AppropriationModalProps.ts
  shared/types/src/common/LectureItemProps.ts
Labels: ♻️ Refactor, ⚙ Setting

#70 Color 16진수에서 theme로 변경
  packages/inside/src/emotion.d.ts
  packages/outside/src/emotion.d.ts
  shared/common/src/components/Header/index.tsx
  shared/common/src/components/ValueInput/index.tsx
  shared/common/src/components/ValueInput/style.ts
  shared/common/src/modals/SelectCalendarModal/index.tsx
  shared/common/src/pages/login/index.tsx
  shared/common/src/pages/signUp/Pagination/Page3/index.tsx
  shared/types/src/common/ValueInputProps.ts
Labels: ⚡️ Simple
