Repository School-of-Company/Bitgouel-Frontend, pull requests merged in 2024-07, with the labels that each got.

#284 [Common] 메인 페이지 스크롤 애니메이션 효과
  package.json
  pnpm-lock.yaml
  shared/common/src/components/FAQSection/index.tsx
  shared/common/src/components/FAQSection/style.ts
  shared/common/src/components/Sliders/style.ts
  shared/common/src/hooks/index.ts
  shared/common/src/hooks/useScroll.tsx
  shared/common/src/pages/home/HomeSection/Section2/index.tsx
  shared/common/src/pages/home/HomeSection/Section2/style.ts
  shared/common/src/pages/home/HomeSection/Section3/index.tsx
  shared/common/src/pages/home/HomeSection/Section3/style.ts
  shared/common/src/pages/home/HomeSection/Section4/index.tsx
  shared/common/src/pages/home/HomeSection/Section4/style.ts
  shared/common/src/pages/home/HomeSection/Section5/index.tsx
  shared/common/src/pages/home/HomeSection/Section5/style.ts
  shared/common/src/pages/home/HomeSection/Section6/index.tsx
  shared/common/src/pages/home/HomeSection/Section7/index.tsx
  shared/common/src/pages/home/HomeSection/Section7/style.ts
  shared/common/src/pages/home/HomeSection/animations.ts
Labels: ⚡️ Simple, ⚡️performance, ✨ Feature

#288 [Outside, Common] 학교 이름 Enum 관리 제거
  packages/outside/src/PageContainer/Club/SchoolListPage/index.tsx
  packages/outside/src/components/SchoolContent/index.tsx
  shared/common/src/components/LectureApplyItem/index.tsx
  shared/common/src/constants/schoolObject.ts
  shared/common/src/constants/signUpObject.ts
  shared/common/src/hooks/useSignUp.tsx
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpScrollContainer/index.tsx
Labels: ⚡️ Simple

#289 [Api, Common] 강의 삭제 개발 및 강의 상세에 버튼 추가
  shared/api/client/src/hooks/lecture/usePostEnrollment.ts
  shared/api/common/src/hooks/lecture/index.ts
  shared/api/common/src/hooks/lecture/useDeleteLecture.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/api/common/src/libs/urlController.ts
  shared/common/src/pages/lecture/detail/index.tsx
  shared/common/src/pages/lecture/detail/style.ts
  shared/common/src/pages/lecture/write/index.tsx
  shared/types/src/common/AppropriationModalProps.ts
Labels: ♻️ Refactor, ✨ Feature, 🎨 Publishing

#294 [Inside, Outside, Common] 카카오 맵 API 사용
  package.json
  packages/inside/src/app/layout.tsx
  packages/outside/src/app/layout.tsx
  packages/outside/src/app/page.tsx
  pnpm-lock.yaml
  shared/common/src/components/KakaoMap/index.tsx
  shared/common/src/components/index.ts
  shared/common/src/pages/lecture/detail/index.tsx
  shared/common/src/pages/lecture/detail/style.ts
Labels: ⚙ Setting, ✨ Feature

#295 [Common] 강의 개설에 주소 추가
  package.json
  pnpm-lock.yaml
  shared/common/src/atoms/index.ts
  shared/common/src/components/KakaoMap/index.tsx
  shared/common/src/modals/LectureSettingModal/LecturePlaceInput/index.tsx
  shared/common/src/modals/LectureSettingModal/LectureSearchComponent/index.tsx
  shared/common/src/modals/LectureSettingModal/LectureSearchComponent/style.ts
  shared/common/src/modals/LectureSettingModal/SearchDivision/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchInstructor/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchLine/index.tsx
  shared/common/src/modals/LectureSettingModal/index.tsx
  shared/common/src/pages/lecture/detail/index.tsx
  shared/common/src/pages/lecture/write/index.tsx
  shared/common/tsconfig.json
  shared/types/src/api/common/LectureDetailResponseTypes.ts
  shared/types/src/api/common/LectureWritePayloadTypes.ts
Labels: ✨ Feature, 🎨 Publishing

#296 [Outside, Common] 다른 목록 관리 모달 퍼블리싱
  packages/outside/src/components/ListManagementContent/index.tsx
  packages/outside/src/modals/ScrollListModal/index.stories.tsx
  packages/storybook/package.json
  packages/storybook/tsconfig.json
  pnpm-lock.yaml
  shared/common/src/assets/svg/AgencyIcon.tsx
  shared/common/src/assets/svg/CompanyIcon.tsx
  shared/common/src/assets/svg/DocumentIcon.tsx
  shared/common/src/assets/svg/GraduateIcon.tsx
  shared/common/src/assets/svg/ListManagement.tsx
  shared/common/src/assets/svg/Minus.tsx
  shared/common/src/assets/svg/PeopleCircle.tsx
  shared/common/src/assets/svg/SchoolBookIcon.tsx
  shared/common/src/assets/svg/UniversityIcon.tsx
  shared/common/src/assets/svg/index.ts
Labels: 🎨 Publishing

#298 [Common] 강의 학기 Enum 변경사항 적용
  shared/common/src/components/LectureItem/index.tsx
  shared/common/src/constants/lectureObject.ts
  shared/common/src/modals/LectureSettingModal/LectureApplyTime/index.tsx
  shared/common/src/modals/LectureSettingModal/LectureSemesterSelect/index.tsx
  shared/common/src/pages/lecture/write/index.tsx
  shared/types/src/api/common/LectureWritePayloadTypes.ts
Labels: ⚡️ Simple

#299 [Admin] 새로운 학교 등록 모달 제작
  packages/outside/src/components/LogoButton/index.tsx
  packages/outside/src/components/SchoolClubFilter/index.tsx
  packages/outside/src/components/SchoolClubFilter/style.ts
  packages/outside/src/components/SchoolClubInput/index.tsx
  packages/outside/src/components/SchoolItem/index.tsx
  packages/outside/src/components/index.ts
  packages/outside/src/modals/CreateSchoolModal/CreateClubItem/index.tsx
  packages/outside/src/modals/CreateSchoolModal/SearchSchoolType/index.tsx
  packages/outside/src/modals/CreateSchoolModal/index.stories.tsx
  packages/outside/src/modals/CreateSchoolModal/index.tsx
  packages/outside/src/modals/index.ts
  shared/common/src/atoms/index.ts
  shared/common/src/modals/LectureSettingModal/LectureApplyTime/index.tsx
  shared/common/src/modals/LectureSettingModal/LectureApplyTime/style.ts
  shared/common/src/modals/LectureSettingModal/LectureEnrollmentDates/index.tsx
  shared/common/src/modals/LectureSettingModal/LecturePlaceInput/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchComponent/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchComponent/style.ts
  shared/common/src/modals/LectureSettingModal/SearchDepartment/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchDivision/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchInstructor/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchLectureType/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchLine/index.tsx
Labels: ✨ Feature, 🎨 Publishing

#303 [Admin, Common] 대학 이름 수정 구현
  packages/outside/src/components/AdminUserItem/CheckboxToggleUserItem/index.tsx
  shared/api/admin/src/hooks/admin/index.ts
  shared/api/admin/src/hooks/admin/useGetUniversity.ts
  shared/api/admin/src/hooks/admin/usePatchUniversity.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/api/common/src/libs/urlController.ts
Labels: ✨ Feature

#307 [Admin] 관리자 컴포넌트 리팩토링
  packages/outside/src/PageContainer/Admin/UserListPage/index.tsx
  packages/outside/src/components/AdminDisplayInfo/UniversityDisplayInfo/index.tsx
  packages/outside/src/components/AdminDisplayInfo/UniversityDisplayInfo/style.ts
  packages/outside/src/components/AdminItemComponent/CompoundAdminItemComponent/ModifyInput/index.tsx
  packages/outside/src/components/AdminItemComponent/CompoundAdminItemComponent/ModifyInput/style.ts
  packages/outside/src/components/AdminItemComponent/CompoundAdminItemComponent/index.tsx
  packages/outside/src/components/AdminItemComponent/CompoundAdminItemComponent/style.ts
  packages/outside/src/components/AdminItemComponent/UniversityItem.tsx
  packages/outside/src/components/AdminItemComponent/index.ts
  packages/outside/src/components/AdminUserItem/CheckboxToggleUserItem/CheckBoxText/index.tsx
  packages/outside/src/components/AdminUserItem/CheckboxToggleUserItem/ToggleItem/index.tsx
  packages/outside/src/components/AdminUserItem/CheckboxToggleUserItem/ToggleItem/style.ts
  packages/outside/src/components/AdminUserItem/CheckboxToggleUserItem/index.tsx
  packages/outside/src/components/AdminUserItem/CheckboxUserItem/index.tsx
  packages/outside/src/components/AdminUserItem/UserItem/index.tsx
  packages/outside/src/components/AdminUserItem/index.ts
  packages/outside/src/components/NewUserList/index.tsx
  packages/outside/src/components/UniversityList/index.tsx
  packages/outside/src/components/WithdrawUserList/index.tsx
  packages/outside/src/components/index.ts
  shared/api/admin/src/hooks/admin/index.ts
  shared/api/admin/src/hooks/index.ts
  shared/api/admin/src/hooks/university/index.ts
  shared/api/admin/src/hooks/university/useDeleteDepartment.ts
  shared/api/admin/src/hooks/university/useDeleteUniversity.ts
  shared/api/admin/src/hooks/university/useGetUniversity.ts
  shared/api/admin/src/hooks/university/usePatchUniversity.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/api/common/src/libs/urlController.ts
  shared/types/src/common/AppropriationModalProps.ts
Labels: ♻️ Refactor, 🎨 Publishing

#309 [Admin] 토글 추가 및 학과 관련 API 연결
  packages/outside/src/components/AdminItemComponent/CompoundAdminItemComponent/ModifyInputComponent/index.tsx
  packages/outside/src/components/AdminItemComponent/CompoundAdminItemComponent/ModifyInputComponent/style.ts
  packages/outside/src/components/AdminItemComponent/CompoundAdminItemComponent/index.tsx
  packages/outside/src/components/AdminItemComponent/CompoundAdminItemComponent/style.ts
  packages/outside/src/components/AdminItemComponent/UniversityItem.tsx
  packages/outside/src/components/UniversityList/index.tsx
  shared/api/admin/src/hooks/university/index.ts
  shared/api/admin/src/hooks/university/useDeleteDepartment.ts
  shared/api/admin/src/hooks/university/usePostDepartment.ts
  shared/api/common/src/libs/api/method.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/api/common/src/libs/urlController.ts
  shared/common/src/assets/svg/AddToggleCancelIcon.tsx
  shared/common/src/assets/svg/index.ts
  shared/types/src/common/AppropriationModalProps.ts
Labels: ✨ Feature, 🎨 Publishing

#314 [Common] LectureStatusEnum 수정
  shared/common/src/pages/lecture/detail/index.tsx
  shared/types/src/api/common/LectureItemType.ts
Labels: ⚡️ Simple

#316 [Client, Common] 강의 수강 신청 취소
  shared/api/client/src/hooks/lecture/index.ts
  shared/api/client/src/hooks/lecture/useDeleteEnrollment.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/api/common/src/libs/urlController.ts
  shared/common/src/pages/lecture/detail/index.tsx
  shared/common/src/pages/lecture/detail/style.ts
  shared/types/src/common/AppropriationModalProps.ts
Labels: ✨ Feature, 🎨 Publishing

#318 [Admin] 학교 생성 모달 서버 연동 및 리퍼블리싱
  packages/outside/src/components/LogoButton/index.tsx
  packages/outside/src/components/SchoolItem/index.tsx
  packages/outside/src/modals/CreateSchoolModal/SearchSchoolType/index.tsx
  packages/outside/src/modals/CreateSchoolModal/index.tsx
  packages/outside/src/modals/CreateSchoolModal/style.ts
  shared/api/admin/src/hooks/admin/index.ts
  shared/api/admin/src/hooks/admin/usePostRegistrationSchool.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/api/common/src/libs/urlController.ts
  shared/common/src/atoms/index.ts
  shared/common/src/modals/LectureSettingModal/SearchComponent/index.tsx
  shared/types/src/api/admin/RegistrationTypes.ts
  shared/types/src/api/admin/index.ts
  shared/types/src/api/common/index.ts
Labels: ⚡️performance, ✨ Feature, 🎨 Publishing

#324 [Api] company API hooks 세팅
  shared/api/admin/src/hooks/company/index.ts
  shared/api/admin/src/hooks/company/useDeleteCompany.ts
  shared/api/admin/src/hooks/company/useGetCompany.ts
  shared/api/admin/src/hooks/company/usePostCompany.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/api/common/src/libs/urlController.ts
Labels: ⚙ Setting, ✨ Feature

#325 [Api] government API hooks 세팅
  shared/api/admin/src/hooks/government/index.ts
  shared/api/admin/src/hooks/government/useDeleteGovernment.ts
  shared/api/admin/src/hooks/government/useGetGovernment.ts
  shared/api/admin/src/hooks/government/usePostGovernment.ts
  shared/api/admin/src/hooks/index.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/api/common/src/libs/urlController.ts
Labels: ⚙ Setting, ✨ Feature

#328 [Admin] 대학 생성 모달 제작
  packages/outside/src/PageContainer/Admin/UniversityPage/index.tsx
  packages/outside/src/components/AdminListComponent/index.ts
  packages/outside/src/components/SchoolInputItem/index.tsx
  packages/outside/src/components/SchoolInputItem/style.ts
  packages/outside/src/components/SchoolItem/index.tsx
  packages/outside/src/components/index.ts
  packages/outside/src/modals/CreateModal/CreateSchoolModal/CreateClubItem/index.tsx
  packages/outside/src/modals/CreateModal/CreateSchoolModal/SearchSchoolType/index.tsx
  packages/outside/src/modals/CreateModal/CreateSchoolModal/index.stories.tsx
  packages/outside/src/modals/CreateModal/CreateSchoolModal/index.tsx
  packages/outside/src/modals/CreateModal/CreateSchoolModal/style.ts
  packages/outside/src/modals/CreateModal/CreateUniversityModal/index.stories.tsx
  packages/outside/src/modals/CreateModal/CreateUniversityModal/index.tsx
  packages/outside/src/modals/CreateModal/CreateUniversityModal/style.ts
  packages/outside/src/modals/CreateModal/index.ts
  packages/outside/src/modals/CreateModal/style.ts
  packages/outside/src/modals/index.ts
  shared/api/admin/src/hooks/university/index.ts
  shared/api/admin/src/hooks/university/usePostUniversity.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/api/common/src/libs/urlController.ts
Labels: ✨ Feature, 🎨 Publishing

#329 [Admin, Types] 기업 목록 제작
  packages/outside/src/PageContainer/Admin/CompanyPage/index.tsx
  packages/outside/src/PageContainer/Admin/NewUserListPage/style.ts
  packages/outside/src/PageContainer/Admin/UserListPage/index.tsx
  packages/outside/src/PageContainer/Admin/UserListPage/style.ts
  packages/outside/src/PageContainer/Admin/WithdrawUserListPage/style.ts
  packages/outside/src/PageContainer/Admin/index.ts
  packages/outside/src/app/main/admin/company/page.tsx
  packages/outside/src/components/AdminDisplayInfo/CompanyDisplayInfo/index.tsx
  packages/outside/src/components/AdminDisplayInfo/index.ts
  packages/outside/src/components/AdminItemComponent/CompanyItem/index.tsx
  packages/outside/src/components/AdminItemComponent/CompoundAdminItemComponent/index.tsx
  packages/outside/src/components/AdminItemComponent/CompoundAdminItemComponent/style.ts
  packages/outside/src/components/AdminItemComponent/UniversityItem/index.tsx
  packages/outside/src/components/AdminItemComponent/index.ts
  packages/outside/src/components/AdminListComponent/style.ts
  packages/outside/src/components/CompanyList/index.tsx
  shared/api/admin/src/hooks/company/useGetCompany.ts
  shared/api/admin/src/hooks/index.ts
  shared/types/src/common/AppropriationModalProps.ts
  shared/types/src/common/LoadingAnimationProps.ts
  shared/types/src/common/NoneResultProps.ts
Labels: ✨ Feature, 🎨 Publishing

#330 [Admin, Types] 유관기관 목록 제작
  packages/outside/src/PageContainer/Admin/GovernmentPage/index.tsx
  packages/outside/src/PageContainer/Admin/index.ts
  packages/outside/src/app/main/admin/government/index.tsx
  packages/outside/src/components/AdminDisplayInfo/GovernmentDisplayInfo/index.tsx
  packages/outside/src/components/AdminDisplayInfo/index.ts
  packages/outside/src/components/AdminItemComponent/CompoundAdminItemComponent/index.tsx
  packages/outside/src/components/AdminItemComponent/GovernmentItem/index.tsx
  packages/outside/src/components/AdminItemComponent/index.ts
  packages/outside/src/components/AdminListComponent/GovernmentList/index.tsx
  shared/types/src/common/AppropriationModalProps.ts
Labels: ✨ Feature, 🎨 Publishing

#336 [Admin, Common] 강의 수정 값 설정 오류
  packages/outside/src/modals/CreateModal/style.ts
  shared/common/src/modals/LectureSettingModal/SearchComponent/index.tsx
  shared/common/src/modals/LectureSettingModal/index.stories.tsx
  shared/common/src/pages/lecture/write/index.tsx
Labels: ⚡️ Simple, 🐞 Bug

#338 [Admin, Common] Compound 컴포넌트 위치 변경
  packages/outside/src/PageContainer/Admin/UserListPage/index.tsx
  packages/outside/src/components/AdminItemComponent/CompanyItem/index.tsx
  packages/outside/src/components/AdminItemComponent/GovernmentItem/index.tsx
  packages/outside/src/components/AdminItemComponent/SchoolItem/ClubItem/index.tsx
  packages/outside/src/components/AdminItemComponent/SchoolItem/index.tsx
  packages/outside/src/components/AdminItemComponent/UniversityItem/index.tsx
  packages/outside/src/components/AdminItemComponent/index.ts
  packages/outside/src/components/AdminListComponent/NewUserList/index.tsx
  packages/outside/src/components/AdminListComponent/WithdrawUserList/index.tsx
  packages/outside/src/components/AdminListComponent/index.ts
  packages/outside/src/components/SchoolClubFilter/index.tsx
  packages/outside/src/components/SchoolClubFilter/style.ts
  packages/outside/src/components/index.ts
  packages/outside/src/modals/CreateModal/CreateSchoolModal/CreateClubItem/index.tsx
  shared/common/src/components/CompoundListItemComponent/ModifyFieldScroll/index.tsx
  shared/common/src/components/CompoundListItemComponent/ModifyFieldScroll/style.ts
  shared/common/src/components/CompoundListItemComponent/ModifyInputComponent/index.tsx
  shared/common/src/components/CompoundListItemComponent/ModifyInputComponent/style.ts
  shared/common/src/components/CompoundListItemComponent/index.tsx
  shared/common/src/components/CompoundListItemComponent/style.ts
  shared/common/src/components/FieldScroll/index.tsx
  shared/common/src/components/FieldScroll/style.ts
  shared/common/src/components/index.ts
Labels: ⚡️ Simple
