Repository School-of-Company/Bitgouel-Frontend, pull requests merged in 2024-06, with the labels that each got.

#218 [Common, Inside, Otuside] 상세 페이지 구조 변경 및 오류 해결
  packages/inside/src/PageContainer/Club/ActivityWritePage/index.tsx
  packages/inside/src/app/main/club/detail/[clubId]/student/detail/[studentId]/activity/create/page.tsx
  packages/inside/src/app/main/club/detail/[clubId]/student/detail/[studentId]/activity/detail/[activityId]/modify/page.tsx
  packages/inside/src/app/main/club/detail/[clubId]/student/detail/[studentId]/activity/detail/[activityId]/page.tsx
  packages/inside/src/app/main/club/detail/[clubId]/student/detail/[studentId]/activity/page.tsx
  packages/inside/src/app/main/club/detail/[clubId]/student/detail/[studentId]/page.tsx
  packages/inside/src/app/main/lecture/detail/[lectureId]/apply/page.tsx
  packages/inside/src/app/main/lecture/detail/[lectureId]/page.tsx
  packages/inside/src/app/main/post/detail/[postId]/modify/page.tsx
  packages/inside/src/app/main/post/detail/[postId]/page.tsx
  packages/inside/src/app/main/post/inquiry/detail/[inquiryId]/modify/page.tsx
  packages/inside/src/app/main/post/inquiry/detail/[inquiryId]/page.tsx
  packages/inside/src/app/main/post/notice/detail/[noticeId]/page.tsx
  packages/outside/src/app/main/club/detail/[clubId]/page.tsx
  packages/outside/src/app/main/club/detail/[clubId]/student/[studentId]/activity/[activityId]/page.tsx
  packages/outside/src/app/main/club/detail/[clubId]/student/[studentId]/activity/page.tsx
  packages/outside/src/app/main/club/detail/[clubId]/student/[studentId]/page.tsx
  packages/outside/src/app/main/lecture/detail/[lectureId]/apply/page.tsx
  packages/outside/src/app/main/lecture/detail/[lectureId]/page.tsx
  packages/outside/src/app/main/post/detail/[postId]/modify/page.tsx
  packages/outside/src/app/main/post/detail/[postId]/page.tsx
  packages/outside/src/app/main/post/inquiry/detail/[inquiryId]/page.tsx
  packages/outside/src/app/main/post/notice/detail/[noticeId]/modify/page.tsx
  packages/outside/src/app/main/post/notice/detail/[noticeId]/page.tsx
  packages/outside/src/components/ClubItem/index.tsx
  shared/api/common/src/libs/api/instance.ts
  shared/common/src/components/ActivityItem/index.tsx
  shared/common/src/components/InquiryItem/index.tsx
  shared/common/src/components/LectureItem/index.tsx
  shared/common/src/components/PostItem/index.tsx
  shared/common/src/pages/activity/detail/index.tsx
  shared/common/src/pages/activity/list/index.tsx
  shared/common/src/pages/club/detail/index.tsx
  shared/common/src/pages/club/student/index.tsx
  shared/common/src/pages/inquiry/detail/index.tsx
  shared/common/src/pages/lecture/detail/index.tsx
  shared/common/src/pages/post/detail/index.tsx
  shared/common/src/pages/post/notice/detail/index.tsx
Labels: ⚡️performance, 🐞 Bug

#221 [Common] 권한에 따른 로그인 후처리 로직 변경
  shared/api/common/src/libs/api/TokenManager.ts
  shared/common/src/components/Auth/Login/LoginForm/LoginButtons/index.tsx
  shared/common/src/components/Auth/Login/LoginForm/index.tsx
Labels: ⚡️performance

#222 [Common] auth 파트 onBlur 적용 및 비밀번호 변경 제작
  shared/api/common/src/hooks/auth/useDeleteLogout.ts
  shared/api/common/src/hooks/my/usePatchPassword.ts
  shared/common/src/components/Auth/Login/LoginForm/LoginInput/Email/index.tsx
  shared/common/src/components/Auth/Login/LoginForm/LoginInput/Password/index.tsx
  shared/common/src/components/Auth/Login/LoginForm/LoginInput/PasswordText/index.tsx
  shared/common/src/components/Auth/Login/LoginForm/LoginInput/PasswordText/style.ts
  shared/common/src/components/ValueInput/index.tsx
  shared/common/src/modals/ChangePwModal/index.stories.tsx
  shared/common/src/modals/ChangePwModal/index.tsx
  shared/common/src/modals/ChangePwModal/style.ts
  shared/common/src/modals/index.ts
  shared/common/src/pages/auth/find/Pagination/EmailCheck/index.tsx
  shared/common/src/pages/auth/find/Pagination/NewPassword/index.tsx
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpPage3/index.tsx
  shared/common/src/pages/my/index.tsx
Labels: ♻️ Refactor, ✨ Feature

#224 [Common] 404 페이지 제작
  .DS_Store
  .gitignore
  packages/inside/src/app/not-found.tsx
  packages/outside/src/app/not-found.tsx
  shared/.DS_Store
  shared/common/.DS_Store
  shared/common/src/.DS_Store
  shared/common/src/assets/.DS_Store
  shared/common/src/pages/404/index.tsx
  shared/common/src/pages/404/style.ts
  shared/common/src/pages/home/index.tsx
  shared/common/src/pages/index.ts
Labels: ✨ Feature, 🎨 Publishing

#225 [Inside, Outside] 파비콘 변경
  packages/inside/src/app/favicon.ico
  packages/outside/src/app/favicon.ico
Labels: ⚡️ Simple, 📝 Docs

#226 [Common] 회원가입 submit 이벤트 추가
  shared/common/src/hooks/index.ts
  shared/common/src/hooks/useSignUp.tsx
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpButtonContainer/index.tsx
  shared/common/src/pages/auth/signUp/index.tsx
  shared/common/src/pages/auth/signUp/style.ts
Labels: ♻️ Refactor, ✨ Feature

#228 [Outside, Common] 적용되어 있지 않은 컴포넌트, 모달에 Story 생성
  packages/outside/src/PageContainer/Admin/NewUserListPage/index.tsx
  packages/outside/src/PageContainer/Admin/NewUserListPage/style.ts
  packages/outside/src/PageContainer/Admin/UserListPage/index.tsx
  packages/outside/src/PageContainer/Admin/UserListPage/style.ts
  packages/outside/src/PageContainer/Admin/WithdrawUserListPage/index.tsx
  packages/outside/src/PageContainer/Admin/WithdrawUserListPage/style.ts
  packages/outside/src/PageContainer/Club/ClubPage/index.tsx
  packages/outside/src/PageContainer/Club/SchoolListPage/index.tsx
  packages/outside/src/components/AdminDisplayInfo/index.tsx
  packages/outside/src/components/AdminDisplayInfo/style.ts
  packages/outside/src/components/ClubBanner/index.stories.tsx
  packages/outside/src/components/ClubBanner/index.tsx
  packages/outside/src/components/index.ts
  shared/api/common/src/libs/api/instance.ts
  shared/common/src/atoms/index.ts
  shared/common/src/components/Auth/Login/LoginBottom/index.stories.tsx
  shared/common/src/components/Auth/Login/LoginForm/LoginButton/index.stories.tsx
  shared/common/src/components/Auth/Login/LoginForm/LoginButton/index.tsx
  shared/common/src/components/Auth/Login/LoginForm/LoginButton/style.ts
  shared/common/src/components/Auth/Login/LoginForm/LoginInput/Email/index.stories.tsx
  shared/common/src/components/Auth/Login/LoginForm/LoginInput/Password/index.stories.tsx
  shared/common/src/components/Auth/Login/LoginForm/LoginInput/PasswordText/index.stories.tsx
  shared/common/src/components/Auth/Login/LoginForm/LoginInput/index.stories.tsx
  shared/common/src/components/Auth/Login/LoginForm/index.stories.tsx
  shared/common/src/components/Auth/Login/LoginForm/index.tsx
  shared/common/src/components/CertificateItem/index.stories.tsx
  shared/common/src/components/CommonCheckBox/index.stories.tsx
  shared/common/src/components/CompleteLectureItem/index.stories.tsx
  shared/common/src/components/FAQAnswerItem/index.tsx
  shared/common/src/components/Header/index.tsx
  shared/common/src/components/LectureApplyItem/index.stories.tsx
  shared/common/src/components/UserItem/index.stories.tsx
  shared/common/src/pages/lecture/detail/index.tsx
Labels: ⚡️ Simple

#231 [Common] JSX문 안에서 length 조건문 수정
  shared/common/src/components/FAQSection/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchDepartment/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchDivision/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchInstructor/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchLectureType/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchLine/index.tsx
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpPage1/index.tsx
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpPage2/index.tsx
  shared/common/src/pages/lecture/apply/index.tsx
  shared/common/src/pages/lecture/page/index.tsx
Labels: ⚡️ Simple

#233 [Common] 로그아웃, 회원탈퇴 모달 제작
  shared/api/common/src/hooks/auth/useDeleteLogout.ts
  shared/api/common/src/hooks/auth/useDeleteWithDraw.ts
  shared/api/common/src/libs/api/TokenManager.ts
  shared/common/src/components/Header/index.tsx
  shared/common/src/pages/my/index.tsx
  shared/types/src/common/AppropriationModalProps.ts
Labels: ✨ Feature, 🎨 Publishing

#234 [Common] ValueInput 컴포넌트 비밀번호 보기 설정
  shared/common/src/atoms/index.ts
  shared/common/src/components/Auth/Login/LoginForm/LoginInput/Email/index.tsx
  shared/common/src/components/Auth/Login/LoginForm/LoginInput/Password/index.tsx
  shared/common/src/components/ValueInput/index.tsx
  shared/common/src/components/ValueInput/style.ts
  shared/common/src/modals/ChangePwModal/index.tsx
  shared/common/src/pages/auth/find/Pagination/EmailCheck/index.tsx
  shared/common/src/pages/auth/find/Pagination/NewPassword/index.tsx
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpPage1/index.tsx
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpPage2/index.tsx
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpPage3/index.tsx
  shared/types/src/common/ValueInputProps.ts
Labels: ✨ Feature

#236 [Common] 공통 리스트 페이지들에 dynamic import 적용
  packages/outside/src/PageContainer/Admin/NewUserListPage/index.tsx
  packages/outside/src/components/NewUserList/index.tsx
  packages/outside/src/components/NewUserList/style.ts
  shared/common/src/atoms/index.ts
  shared/common/src/components/InquiryContainer/InquiryList/index.tsx
  shared/common/src/components/InquiryContainer/InquiryList/style.ts
  shared/common/src/components/InquiryContainer/InquirySearch/index.tsx
  shared/common/src/components/InquiryContainer/InquirySearch/style.ts
  shared/common/src/components/InquiryContainer/index.tsx
  shared/common/src/components/ListComponents/LectureApplyList/index.tsx
  shared/common/src/components/ListComponents/LectureApplyList/style.ts
  shared/common/src/components/ListComponents/LectureList/index.tsx
  shared/common/src/components/ListComponents/NoticeList/index.tsx
  shared/common/src/components/ListComponents/PostList/index.tsx
  shared/common/src/components/ListComponents/PostList/style.ts
  shared/common/src/components/index.ts
  shared/common/src/pages/inquiry/page/index.tsx
  shared/common/src/pages/lecture/apply/index.tsx
  shared/common/src/pages/lecture/apply/style.ts
  shared/common/src/pages/lecture/detail/index.tsx
  shared/common/src/pages/lecture/page/index.tsx
  shared/common/src/pages/post/notice/page/index.tsx
  shared/common/src/pages/post/page/index.tsx
  shared/types/src/common/AppropriationModalProps.ts
Labels: ♻️ Refactor, ⚡️performance

#237 [Common, Outside] 검색 컴포넌트 모듈화
  packages/outside/src/PageContainer/Admin/NewUserListPage/index.tsx
  packages/outside/src/PageContainer/Admin/UserListPage/index.tsx
  packages/outside/src/components/AdminDisplayInfo/NewDisplayInfo/style.ts
  packages/outside/src/components/AdminDisplayInfo/UserDisplayInfo/style.ts
  packages/outside/src/components/AdminDisplayInfo/WithdrawDisplayInfo/style.ts
  packages/outside/src/components/WithdrawUserContainter/index.tsx
  shared/common/src/components/InquiryContainer/InquirySearch/index.tsx
  shared/common/src/components/InquiryContainer/InquirySearch/style.ts
  shared/common/src/components/InquiryContainer/index.tsx
  shared/common/src/components/SearchComponent/index.tsx
  shared/common/src/components/SearchComponent/style.ts
  shared/common/src/components/index.ts
  shared/common/src/modals/FilterModal/index.tsx
  shared/common/src/styles/pageLayout.ts
  shared/types/src/common/FilterModalProps.ts
  shared/types/src/common/index.ts
Labels: ♻️ Refactor

#238 [Common] Home 페이지 섹션 컴포넌트 분리
  shared/common/src/pages/home/HomeSection/Section1/index.tsx
  shared/common/src/pages/home/HomeSection/Section1/style.ts
  shared/common/src/pages/home/HomeSection/Section2/index.tsx
  shared/common/src/pages/home/HomeSection/Section2/style.ts
  shared/common/src/pages/home/HomeSection/Section3/index.tsx
  shared/common/src/pages/home/HomeSection/Section3/style.ts
  shared/common/src/pages/home/HomeSection/Section4/index.tsx
  shared/common/src/pages/home/HomeSection/Section4/style.ts
  shared/common/src/pages/home/HomeSection/Section5/index.tsx
  shared/common/src/pages/home/HomeSection/Section5/style.ts
  shared/common/src/pages/home/HomeSection/Section6/index.tsx
  shared/common/src/pages/home/HomeSection/Section7/index.tsx
  shared/common/src/pages/home/HomeSection/Section7/style.ts
  shared/common/src/pages/home/HomeSection/Section8/index.tsx
  shared/common/src/pages/home/HomeSection/Section8/style.ts
  shared/common/src/pages/home/HomeSection/index.ts
  shared/common/src/pages/home/index.tsx
  shared/common/src/pages/home/style.ts
  shared/common/src/styles/homeStyle.ts
  shared/common/src/styles/index.ts
  shared/common/tsconfig.json
Labels: ♻️ Refactor

#239 [Common] 헤더 내 정보 페이지 버튼 제한
  shared/common/src/components/Header/index.tsx
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#241 [Common] 비밀번호 오류 보여주기
  shared/common/src/components/Auth/Login/LoginForm/index.tsx
Labels: 1️⃣ Priority: High, ⚡️ Simple, 🐞 Bug

#244 [Outside] FAQ 글자 제한 및 텍스트 리셋
  shared/common/src/components/FAQAnswerItem/index.tsx
Labels: 1️⃣ Priority: High, ♻️ Refactor

#243 [Inside, Outside] outside app directory 변경
  packages/inside/src/PageContainer/Club/ActivityWritePage/index.tsx
  packages/outside/src/PageContainer/Admin/UserListPage/index.tsx
  packages/outside/src/PageContainer/Admin/WithdrawUserListPage/index.tsx
  packages/outside/src/app/main/club/detail/[clubId]/student/detail/[studentId]/activity/[activityId]/page.tsx
  packages/outside/src/app/main/club/detail/[clubId]/student/detail/[studentId]/activity/page.tsx
  packages/outside/src/app/main/club/detail/[clubId]/student/detail/[studentId]/page.tsx
  shared/common/src/components/InquiryContainer/index.tsx
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#248 [Outside] 동아리 존재 유무 표시
  packages/outside/src/PageContainer/Club/ClubPage/index.tsx
  packages/outside/src/PageContainer/Club/ClubPage/style.ts
  packages/outside/src/PageContainer/Club/SchoolListPage/index.tsx
  shared/api/admin/src/hooks/club/useGetClubList.ts
  shared/types/src/api/client/SchoolClubListResponseTypes.ts
Labels: 1️⃣ Priority: High, ♻️ Refactor

#247 [Outside] 유저 검색 공백 제거 알림 추가
  packages/outside/src/PageContainer/Admin/UserListPage/index.tsx
  packages/outside/src/components/ClubItem/index.tsx
  shared/common/src/components/InquiryContainer/InquirySearch/index.tsx
Labels: 0️⃣ Priority: Critical

#250 [Common, Outside] 유효하지 않은 링크를 입력했을 때 오류 보여주기
  packages/outside/src/PageContainer/Post/NoticeWritePage/index.tsx
  shared/api/common/src/hooks/post/usePatchPost.ts
  shared/api/common/src/hooks/post/usePostPost.ts
  shared/common/src/pages/post/write/index.tsx
Labels: 1️⃣ Priority: High, 🐞 Bug

#253 [Inside, Outside, Common] authority Context API로 변경
  packages/inside/src/app/customProvider.tsx
  packages/inside/src/app/layout.tsx
  packages/outside/src/PageContainer/Post/NoticeWritePage/index.tsx
  packages/outside/src/app/customProvider.tsx
  packages/outside/src/app/layout.tsx
  packages/outside/src/app/recoilRootProvider.tsx
  shared/api/common/src/libs/api/TokenManager.ts
  shared/common/src/components/CertificateItem/index.tsx
  shared/common/src/components/FAQAnswerItem/index.tsx
  shared/common/src/components/PrivateRouter/index.tsx
  shared/common/src/contexts/authority/AuthorityContext.ts
  shared/common/src/contexts/authority/index.ts
  shared/common/src/contexts/index.ts
  shared/common/src/layouts/GlobalLayout.tsx
  shared/common/src/pages/activity/detail/index.tsx
  shared/common/src/pages/activity/list/index.tsx
  shared/common/src/pages/club/detail/index.tsx
  shared/common/src/pages/club/student/index.tsx
  shared/common/src/pages/lecture/detail/index.tsx
  shared/common/src/pages/lecture/page/index.tsx
  shared/common/src/pages/post/detail/index.tsx
  shared/common/src/pages/post/notice/detail/index.tsx
  shared/common/src/pages/post/page/index.tsx
  shared/common/src/pages/post/write/index.tsx
  shared/types/src/api/common/MyPageResponseTypes.ts
  shared/types/src/api/common/TokensTypes.ts
Labels: 1️⃣ Priority: High, ⚙ Setting, ⚡️performance

#255 [Common, Inside, Outside] AppropriationModal 버튼 연속 처리 방지
  packages/inside/src/PageContainer/Club/ActivityWritePage/index.tsx
  packages/inside/src/PageContainer/Inquiry/InquiryWritePage/index.tsx
  packages/outside/src/PageContainer/Post/NoticeWritePage/index.tsx
  packages/outside/src/components/NewUserList/index.tsx
  packages/outside/src/components/WithdrawUserContainter/index.tsx
  shared/api/client/src/hooks/activity/useDeleteActivityInformationRemove.ts
  shared/api/common/src/hooks/my/usePatchPassword.ts
  shared/api/common/src/hooks/post/usePatchPost.ts
  shared/api/common/src/hooks/post/usePostPost.ts
  shared/common/src/components/Auth/Login/LoginForm/LoginInput/Email/index.tsx
  shared/common/src/components/CertificateItem/index.tsx
  shared/common/src/components/FAQAnswerItem/index.tsx
  shared/common/src/components/Header/index.tsx
  shared/common/src/components/MyContent/index.tsx
  shared/common/src/components/MyContent/style.ts
  shared/common/src/modals/AppropriationModal/index.tsx
  shared/common/src/modals/AppropriationModal/style.ts
  shared/common/src/modals/InquiryAnswerModal/index.tsx
  shared/common/src/pages/activity/detail/index.tsx
  shared/common/src/pages/club/student/index.tsx
  shared/common/src/pages/home/HomeSection/Section8/index.tsx
  shared/common/src/pages/inquiry/detail/index.tsx
  shared/common/src/pages/lecture/create/index.tsx
  shared/common/src/pages/lecture/detail/index.tsx
  shared/common/src/pages/my/index.tsx
  shared/common/src/pages/post/detail/index.tsx
  shared/common/src/pages/post/notice/detail/index.tsx
  shared/common/src/pages/post/write/index.tsx
  shared/types/src/api/common/PostDetailResponseTypes.ts
  shared/types/src/api/common/PostModifyPayloadTypes.ts
  shared/types/src/api/common/PostPayloadTypes.ts
  shared/types/src/api/common/index.ts
  shared/types/src/common/AppropriationModalProps.ts
Labels: ♻️ Refactor, ⚡️performance

#256 [Common, Inside, Outside] 검색 결과가 없을때 컴포넌트 제작
  packages/outside/src/PageContainer/Admin/UserListPage/index.tsx
  packages/outside/src/components/NewUserList/index.tsx
  packages/outside/src/components/WithdrawUserContainter/index.tsx
  shared/common/src/assets/svg/WhiteBox.tsx
  shared/common/src/assets/svg/index.ts
  shared/common/src/components/InquiryContainer/InquiryList/index.tsx
  shared/common/src/components/InquiryContainer/index.tsx
  shared/common/src/components/ListComponents/LectureApplyList/index.tsx
  shared/common/src/components/ListComponents/LectureList/index.tsx
  shared/common/src/components/ListComponents/NoticeList/index.tsx
  shared/common/src/components/ListComponents/PostList/index.tsx
  shared/common/src/components/NoneResult/index.stories.tsx
  shared/common/src/components/NoneResult/index.tsx
  shared/common/src/components/NoneResult/style.ts
  shared/common/src/components/PostItem/index.stories.tsx
  shared/common/src/components/index.ts
  shared/common/src/pages/activity/list/index.tsx
  shared/common/src/pages/club/detail/index.tsx
  shared/common/src/pages/post/page/index.tsx
Labels: ✨ Feature, 🎨 Publishing

#257 [Common] 강의 생성 시 변경 사항 반영
  packages/outside/src/app/main/my/page.tsx
  shared/common/src/modals/LectureSettingModal/LectureApplyTime/index.tsx
  shared/common/src/modals/LectureSettingModal/LectureEnrollmentDates/index.tsx
  shared/common/src/modals/LectureSettingModal/LectureMaxInput/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchDivision/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchInstructor/index.tsx
  shared/common/src/modals/LectureSettingModal/index.tsx
  shared/common/src/pages/lecture/create/index.tsx
Labels: ⚡️ Simple

#258 [Common, Inside, Outside] ~불러오는 중... 컴포넌트 제작
  packages/outside/src/PageContainer/Admin/UserListPage/index.tsx
  packages/outside/src/PageContainer/Club/ClubPage/index.tsx
  packages/outside/src/components/NewUserList/index.tsx
  packages/outside/src/components/WithdrawUserContainter/index.tsx
  shared/common/src/assets/gif/Loading.gif
  shared/common/src/assets/gif/index.ts
  shared/common/src/assets/index.ts
  shared/common/src/components/InquiryContainer/InquiryList/index.tsx
  shared/common/src/components/ListComponents/LectureApplyList/index.tsx
  shared/common/src/components/ListComponents/LectureList/index.tsx
  shared/common/src/components/ListComponents/NoticeList/index.tsx
  shared/common/src/components/ListComponents/PostList/index.tsx
  shared/common/src/components/NoneResult/index.tsx
  shared/common/src/components/Sliders/ClubListSlider/index.tsx
  shared/common/src/components/WaitingAnimation/index.stories.tsx
  shared/common/src/components/WaitingAnimation/index.tsx
  shared/common/src/components/WaitingAnimation/style.ts
  shared/common/src/components/index.ts
  shared/common/src/pages/activity/list/index.tsx
  shared/common/src/pages/club/detail/index.tsx
  shared/types/src/common/LoadingAnimationProps.ts
  shared/types/src/common/NoneResultProps.ts
  shared/types/src/common/index.ts
Labels: ♻️ Refactor, 🎨 Publishing

#262 [Common] 게시자 표시
  shared/common/src/pages/post/detail/index.tsx
  shared/common/src/pages/post/detail/style.ts
  shared/common/src/pages/post/notice/detail/index.tsx
  shared/common/src/pages/post/notice/detail/style.ts
Labels: ⚡️ Simple, 🎨 Publishing

#259 [Common] FAQ 질문 state를 useState에서 useReducer로 변경
  pnpm-lock.yaml
  shared/common/src/components/FAQAnswerItem/index.tsx
Labels: 3️⃣ Priority: Low, ♻️ Refactor

#261 [Inside, Outside, Storybook] 스토리북 tsconfig 설정
  packages/inside/src/app/layout.tsx
  packages/inside/src/app/main/club/detail/[clubId]/student/detail/[studentId]/activity/create/page.tsx
  packages/inside/src/app/main/club/detail/[clubId]/student/detail/[studentId]/activity/detail/[activityId]/modify/page.tsx
  packages/inside/src/app/main/post/inquiry/create/page.tsx
  packages/inside/src/app/main/post/inquiry/detail/[inquiryId]/modify/page.tsx
  packages/inside/tsconfig.json
  packages/outside/src/PageContainer/Admin/UserListPage/index.tsx
  packages/outside/src/PageContainer/Admin/WithdrawUserListPage/index.tsx
  packages/outside/src/PageContainer/Club/ClubPage/index.tsx
  packages/outside/src/PageContainer/Club/SchoolListPage/index.tsx
  packages/outside/src/app/customProvider.tsx
  packages/outside/src/app/layout.tsx
  packages/outside/src/app/main/admin/new/page.tsx
  packages/outside/src/app/main/admin/page.tsx
  packages/outside/src/app/main/admin/withdraw/page.tsx
  packages/outside/src/app/main/club/page.tsx
  packages/outside/src/app/main/club/school/page.tsx
  packages/outside/src/app/main/post/notice/create/page.tsx
  packages/outside/src/app/main/post/notice/detail/[noticeId]/modify/page.tsx
  packages/outside/src/components/AdminDisplayInfo/WithdrawDisplayInfo/style.ts
  packages/outside/src/components/ClubBanner/index.stories.tsx
  packages/outside/src/components/ClubBanner/index.tsx
  packages/outside/src/components/WithdrawUserContainter/index.tsx
  packages/outside/src/modals/SchoolFilterModal/index.tsx
  packages/outside/tsconfig.json
  packages/storybook/.storybook/preview.js
  packages/storybook/package.json
  packages/storybook/tsconfig.json
  pnpm-lock.yaml
  shared/common/src/components/index.ts
  shared/common/src/layouts/CustomProvider/index.tsx
  shared/common/src/layouts/index.ts
Labels: 🐞 Bug

#263 [Common] snake 케이스로의 형식 변경
  packages/inside/src/PageContainer/Inquiry/InquiryWritePage/index.tsx
  packages/outside/src/PageContainer/Post/NoticeWritePage/index.tsx
  shared/common/src/components/Auth/Login/LoginForm/LoginInput/Password/index.tsx
  shared/common/src/components/FAQAnswerItem/index.tsx
  shared/common/src/modals/ChangePwModal/index.tsx
  shared/common/src/modals/LectureSettingModal/LectureMaxInput/index.tsx
  shared/common/src/pages/lecture/create/index.tsx
  shared/common/src/pages/post/write/index.tsx
Labels: ♻️ Refactor

#264 [Common] 푸터의 내용을 변경합니다
  shared/common/src/pages/home/HomeSection/Section8/index.tsx
Labels: ♻️ Refactor, 🎨 Publishing

#266 [Common, Inside, Outside] 트위터 카드 설정 및 헤더의 심볼 변경
  packages/inside/src/app/layout.tsx
  packages/outside/src/app/layout.tsx
  shared/common/src/assets/images/symbol1.avif
  shared/common/src/assets/images/symbol2.avif
Labels: ♻️ Refactor, ⚙ Setting

#267 [Common] 강의 생성 변경사항 적용
  shared/common/src/atoms/index.ts
  shared/common/src/modals/LectureSettingModal/LectureApplyTime/index.tsx
  shared/common/src/modals/LectureSettingModal/LectureEnrollmentDates/index.tsx
  shared/common/src/modals/LectureSettingModal/LectureMaxInput/index.tsx
  shared/common/src/modals/LectureSettingModal/LectureSearchComponent/index.tsx
  shared/common/src/modals/LectureSettingModal/LectureSearchComponent/style.ts
  shared/common/src/modals/LectureSettingModal/SearchDepartment/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchDivision/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchInstructor/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchLectureType/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchLine/index.tsx
  shared/common/src/modals/LectureSettingModal/index.tsx
  shared/common/src/modals/LectureSettingModal/style.ts
  shared/common/src/pages/lecture/create/index.tsx
Labels: 1️⃣ Priority: High, ♻️ Refactor, ⚡️performance

#269 [Common] 강의 수강 신청일 수정
  shared/common/src/modals/LectureSettingModal/SearchLectureType/index.tsx
  shared/common/src/pages/lecture/detail/index.tsx
Labels: ⚡️ Simple, 🐞 Bug

#271 [Common] 회원가입 payload 수정
  shared/common/src/constants/signUpObject.ts
  shared/common/src/hooks/useSignUp.tsx
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpScrollContainer/index.tsx
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpScrollContainer/style.ts
Labels: ⚡️ Simple

#274 [Inside, Outside, Common] 강의 상세 데이터 작성 페이지에 적용 및 PrivateRouter 트러블 슈팅
  packages/inside/src/PageContainer/Club/ActivityWritePage/index.tsx
  packages/inside/src/app/main/lecture/create/page.tsx
  packages/inside/src/app/main/lecture/detail/[lectureId]/modify/page.tsx
  packages/outside/src/PageContainer/Post/NoticeWritePage/index.tsx
  packages/outside/src/app/main/lecture/create/page.tsx
  packages/outside/src/app/main/lecture/detail/[lectureId]/modify/page.tsx
  shared/common/src/components/CertificateItem/index.tsx
  shared/common/src/components/MyContent/index.tsx
  shared/common/src/components/PrivateRouter/index.tsx
  shared/common/src/contexts/authority/AuthorityContext.ts
  shared/common/src/layouts/CustomProvider/index.tsx
  shared/common/src/pages/activity/detail/index.tsx
  shared/common/src/pages/activity/list/index.tsx
  shared/common/src/pages/club/student/index.tsx
  shared/common/src/pages/index.ts
  shared/common/src/pages/lecture/apply/index.tsx
  shared/common/src/pages/lecture/create/style.ts
  shared/common/src/pages/lecture/index.ts
  shared/common/src/pages/lecture/write/index.tsx
  shared/common/src/pages/lecture/write/style.ts
  shared/common/src/pages/post/detail/index.tsx
  shared/common/src/pages/post/notice/detail/index.tsx
  shared/common/src/pages/post/page/index.tsx
  shared/common/src/pages/post/write/index.tsx
  shared/types/src/api/common/LectureDetailResponseTypes.ts
  shared/types/src/api/common/LectureItemType.ts
Labels: ♻️ Refactor, ✨ Feature

#279 [Outside] 학교 선택 모달 재사용
  packages/outside/src/components/ClubBanner/index.tsx
  packages/outside/src/components/SchoolContent/index.tsx
  packages/outside/src/components/SchoolContent/style.ts
  packages/outside/src/modals/SchoolFilterModal/index.stories.tsx
  packages/outside/src/modals/SchoolFilterModal/index.tsx
  packages/outside/src/modals/ScrollListModal/index.stories.tsx
  packages/outside/src/modals/ScrollListModal/index.tsx
  packages/outside/src/modals/ScrollListModal/style.ts
  packages/outside/src/modals/index.ts
Labels: ♻️ Refactor

#281 [Common, Outside] 다른 목록 관리 모달 제작
  packages/outside/src/PageContainer/Admin/NewUserListPage/index.tsx
  packages/outside/src/PageContainer/Admin/UserListPage/index.tsx
  packages/outside/src/PageContainer/Admin/WithdrawUserListPage/index.tsx
  packages/outside/src/components/ListManagementContent/index.tsx
  packages/outside/src/components/ListManagementContent/style.ts
  packages/outside/src/components/index.ts
  packages/outside/src/modals/ScrollListModal/index.tsx
  shared/common/src/assets/svg/DocumentIcon.tsx
  shared/common/src/assets/svg/ListManagement.tsx
  shared/common/src/assets/svg/Minus.tsx
  shared/common/src/assets/svg/People.tsx
  shared/common/src/assets/svg/Plus.tsx
  shared/common/src/assets/svg/index.ts
Labels: ✨ Feature, 🎨 Publishing
