Repository School-of-Company/Bitgouel-Frontend, pull requests merged in 2024-04, with the labels that each got.

#161 [Inside, Outside] 폰트 최적화
  packages/inside/public/fonts/woff/Pretendard-Black.woff
  packages/inside/public/fonts/woff/Pretendard-Bold.woff
  packages/inside/public/fonts/woff/Pretendard-ExtraBold.woff
  packages/inside/public/fonts/woff/Pretendard-ExtraLight.woff
  packages/inside/public/fonts/woff/Pretendard-Light.woff
  packages/inside/public/fonts/woff/Pretendard-Thin.woff
  packages/inside/public/fonts/woff2/Pretendard-Black.woff2
  packages/inside/public/fonts/woff2/Pretendard-Bold.woff2
  packages/inside/public/fonts/woff2/Pretendard-ExtraBold.woff2
  packages/inside/public/fonts/woff2/Pretendard-ExtraLight.woff2
  packages/inside/public/fonts/woff2/Pretendard-Light.woff2
  packages/inside/public/fonts/woff2/Pretendard-Thin.woff2
  packages/inside/src/app/fonts/woff/Pretendard-Medium.woff
  packages/inside/src/app/fonts/woff/Pretendard-Regular.woff
  packages/inside/src/app/fonts/woff/Pretendard-SemiBold.woff
  packages/inside/src/app/fonts/woff2/Pretendard-Medium.woff2
  packages/inside/src/app/fonts/woff2/Pretendard-Regular.woff2
  packages/inside/src/app/fonts/woff2/Pretendard-SemiBold.woff2
  packages/inside/src/app/layout.tsx
  packages/inside/src/app/main/club/page.tsx
  packages/inside/src/styles/font.css
  packages/outside/public/fonts/woff/Pretendard-Black.woff
  packages/outside/public/fonts/woff/Pretendard-Bold.woff
  packages/outside/public/fonts/woff/Pretendard-ExtraBold.woff
  packages/outside/public/fonts/woff/Pretendard-ExtraLight.woff
  packages/outside/public/fonts/woff/Pretendard-Light.woff
  packages/outside/public/fonts/woff/Pretendard-Thin.woff
  packages/outside/public/fonts/woff2/Pretendard-Black.woff2
  packages/outside/public/fonts/woff2/Pretendard-Bold.woff2
  packages/outside/public/fonts/woff2/Pretendard-ExtraBold.woff2
  packages/outside/public/fonts/woff2/Pretendard-ExtraLight.woff2
  packages/outside/public/fonts/woff2/Pretendard-Light.woff2
  packages/outside/public/fonts/woff2/Pretendard-Thin.woff2
  packages/outside/src/app/fonts/woff/Pretendard-Medium.woff
  packages/outside/src/app/fonts/woff/Pretendard-Regular.woff
  packages/outside/src/app/fonts/woff/Pretendard-SemiBold.woff
  packages/outside/src/app/fonts/woff2/Pretendard-Medium.woff2
  packages/outside/src/app/fonts/woff2/Pretendard-Regular.woff2
  packages/outside/src/app/fonts/woff2/Pretendard-SemiBold.woff2
  packages/outside/src/app/layout.tsx
  packages/outside/src/styles/font.css
  packages/storybook/.storybook/preview.js
  shared/common/src/styles/globals.css
Labels: ⚡️performance

#160 [Inside, Admin] 학생 페이지 자격증 refecth 로직 수정
  shared/api/client/src/hooks/certificate/usePatchModifyCertificate.ts
  shared/common/src/components/CertificateItem/index.tsx
  shared/common/src/pages/club/student/index.tsx
  shared/types/src/api/common/CertificateProps.ts
Labels: ♻️ Refactor, ⚡️ Simple, ⚡️performance

#162 [Inside, Outside] 이미지 모듈 sharp 추가, avif 형식으로 포맷
  packages/inside/next.config.js
  packages/inside/package.json
  packages/inside/src/app/layout.tsx
  packages/outside/next.config.js
  packages/outside/package.json
  pnpm-lock.yaml
Labels: ⚡️performance

#164 [Common] 헤더의 강의 필터 제거
  shared/common/src/components/Header/index.tsx
Labels: ⚡️performance

#165 [Common, Inside, Outside] 날짜 변환 방식을 dayjs로 변경
  .DS_Store
  package.json
  packages/inside/src/PageContainer/Club/ActivityCreatePage/index.tsx
  packages/inside/src/PageContainer/Club/ActivityModifyPage/index.tsx
  packages/inside/src/PageContainer/Club/ActivityModifyPage/style.ts
  packages/inside/src/PageContainer/Club/ActivityWritePage/index.tsx
  packages/inside/src/PageContainer/Club/ActivityWritePage/style.ts
  packages/inside/src/PageContainer/Club/index.ts
  packages/inside/src/app/main/club/[clubId]/student/[studentId]/activity/[activityId]/modify/page.tsx
  packages/inside/src/app/main/club/[clubId]/student/[studentId]/activity/create/page.tsx
  pnpm-lock.yaml
  shared/api/common/src/hooks/activity/useGetActivityDetail.ts
  shared/common/package.json
  shared/common/src/.DS_Store
  shared/common/src/components/ActivityItem/index.tsx
  shared/common/src/components/InquiryItem/index.tsx
  shared/common/src/components/LectureItem/index.tsx
  shared/common/src/components/PostItem/index.tsx
  shared/common/src/index.ts
  shared/common/src/pages/activity/detail/index.tsx
  shared/common/src/pages/activity/index.ts
  shared/common/src/pages/activity/list/index.tsx
  shared/common/src/pages/activity/write/style.ts
  shared/common/src/pages/club/student/index.tsx
  shared/common/src/pages/index.ts
  shared/common/src/pages/inquiry/detail/index.tsx
  shared/common/src/pages/lecture/detail/index.tsx
  shared/common/src/pages/my/index.tsx
  shared/common/src/pages/post/detail/index.tsx
  shared/common/src/pages/post/notice/detail/index.tsx
  shared/common/src/utils/date.ts
  shared/common/src/utils/index.ts
  shared/types/src/common/ActivityDetailProps.ts
Labels: ♻️ Refactor, ⚡️performance

#167 Revert "[Common] 남아있는 상대경로 절대경로로 수정"
  shared/api/common/src/hooks/activity/useGetActivityList.ts
  shared/common/src/components/Sequence/index.tsx
  shared/common/src/components/Sliders/ClubListSlider/index.tsx
  shared/common/src/components/Sliders/CompanyListSlider/index.tsx
  shared/common/src/components/ValueInput/index.tsx
  shared/common/src/modals/AppropriationModal/index.tsx
  shared/common/src/modals/InquiryAnswerModal/index.tsx
  shared/common/src/pages/signUp/Pagination/SignUpScrollContainer/index.tsx
  shared/types/src/index.ts
  shared/types/src/inside/LectureApplyModalProps.ts
  shared/types/src/inside/index.ts
Labels: 🐞 Bug

#168 [Inside, Common] 남아있는 상대 경로 수정 및 학생활동 글자 수정
  packages/inside/src/PageContainer/Club/ActivityWritePage/index.tsx
  shared/api/common/src/hooks/activity/useGetActivityList.ts
  shared/api/tsconfig.json
  shared/common/src/components/Header/index.tsx
  shared/common/src/components/Sequence/index.tsx
  shared/common/src/components/ValueInput/index.tsx
  shared/common/src/modals/AppropriationModal/index.tsx
  shared/common/src/modals/InquiryAnswerModal/index.tsx
  shared/common/src/pages/signUp/Pagination/SignUpScrollContainer/index.tsx
  shared/common/tsconfig.json
  shared/types/src/index.ts
  shared/types/src/inside/LectureApplyModalProps.ts
  shared/types/src/inside/index.ts
Labels: ⚡️ Simple

#171 [Common] 강의 신청자 명단 출력 버튼 추가
  shared/common/src/assets/svg/PrintIcon.tsx
  shared/common/src/assets/svg/index.ts
  shared/common/src/hooks/useDownload.ts
  shared/common/src/pages/lecture/page/index.tsx
Labels: 🎨 Publishing

#172 [Common] 헤더 쓰로틀링
  shared/common/src/components/Header/index.tsx
Labels: ⚡️performance

#173 [Common] 강의 페이지네이션 추가
  .DS_Store
  packages/outside/tsconfig.json
  shared/common/src/assets/svg/ArrowIcon.tsx
  shared/common/src/assets/svg/CheckBoxIcon.tsx
  shared/common/src/assets/svg/DoubleArrowIcon.tsx
  shared/common/src/assets/svg/InClubArrow.tsx
  shared/common/src/assets/svg/index.ts
  shared/common/src/components/FAQSection/index.tsx
  shared/common/src/components/PaginationPages/index.stories.tsx
  shared/common/src/components/PaginationPages/index.tsx
  shared/common/src/components/PaginationPages/style.ts
  shared/common/src/components/index.ts
  shared/common/src/hooks/useModal.ts
  shared/common/src/pages/lecture/page/index.tsx
  shared/common/src/pages/lecture/page/style.ts
  shared/types/src/api/client/ActivityInformationTypes.ts
  shared/types/src/api/common/LectureListResponseTypes.ts
  shared/types/src/api/common/PageTypes.ts
  shared/types/src/api/common/PostListResponseTypes.ts
  shared/types/src/api/common/index.ts
  shared/types/src/common/PaginationPagesProps.ts
  shared/types/src/common/index.ts
Labels: ✨ Feature, 🎨 Publishing

#174 [Outside, Common] 강의 이수 여부 페이지 퍼블리싱
  packages/outside/src/PageContainer/Admin/NewUserListPage/index.tsx
  packages/outside/src/PageContainer/Admin/UserListPage/index.tsx
  packages/outside/src/PageContainer/Admin/WithdrawUserListPage/index.tsx
  packages/outside/src/PageContainer/Lecture/LectureCreatePage/index.tsx
  packages/outside/src/app/main/lecture/[lectureId]/apply/page.tsx
  shared/api/common/src/libs/api/instance.ts
  shared/common/src/assets/svg/CheckBoxIcon.tsx
  shared/common/src/components/ApplyItem/index.stories.tsx
  shared/common/src/components/ApplyItem/index.tsx
  shared/common/src/components/ApplyItem/style.ts
  shared/common/src/components/CommonCheckBox/index.tsx
  shared/common/src/components/CommonCheckBox/style.ts
  shared/common/src/components/FAQSection/index.tsx
  shared/common/src/components/UserItem/index.tsx
  shared/common/src/components/UserItem/style.ts
  shared/common/src/components/index.ts
  shared/common/src/index.ts
  shared/common/src/pages/index.ts
  shared/common/src/pages/lecture/apply/index.tsx
  shared/common/src/pages/lecture/apply/style.ts
  shared/common/src/pages/lecture/index.ts
  shared/common/src/utils/handleSelect.ts
  shared/common/src/utils/index.ts
  shared/types/src/common/UserItemProps.ts
Labels: ✨ Feature

#175 [Admin] 동아리 학교 조회
  packages/outside/src/PageContainer/Club/ClubPage/index.tsx
  packages/outside/src/PageContainer/Club/ClubPage/style.ts
  packages/outside/src/PageContainer/Club/SchoolListPage/index.tsx
  packages/outside/src/PageContainer/Club/index.ts
  packages/outside/src/app/main/club/page.tsx
  packages/outside/src/app/main/club/school/page.tsx
  packages/outside/src/components/SchoolFilter/index.tsx
  packages/outside/src/components/SchoolFilter/style.ts
  packages/outside/src/components/index.ts
  packages/outside/src/modals/SchoolFilterModal/index.tsx
  packages/outside/src/modals/SchoolFilterModal/style.ts
  shared/common/src/index.ts
  shared/common/src/pages/activity/list/index.tsx
Labels: ♻️ Refactor, ⚡️performance

#176 interceptors, tokenManager 환경 세팅
  packages/outside/src/PageContainer/Club/ClubPage/index.tsx
  packages/outside/src/PageContainer/Club/SchoolListPage/index.tsx
  shared/api/admin/club/useGetClubList.ts
  shared/api/admin/club/useGetSchoolClubList.ts
  shared/api/common/src/hooks/auth/usePostLogin.ts
  shared/api/common/src/libs/api/TokenManager.ts
  shared/api/common/src/libs/api/instance.ts
  shared/common/src/pages/login/index.tsx
Labels: ⚙ Setting, ⚡️performance

#177 [Common] 회원가입 유관기관 권한 프로세스 수정
  shared/api/common/src/hooks/auth/usePostBbozzakSignUp.ts
  shared/api/common/src/hooks/auth/usePostTeacherSignUp.ts
  shared/common/src/atoms/index.ts
  shared/common/src/pages/find/Pagination/ChangePasswordSuccess/index.tsx
  shared/common/src/pages/lecture/page/index.tsx
  shared/common/src/pages/signUp/Pagination/SignUpButtonContainer/index.tsx
  shared/common/src/pages/signUp/Pagination/SignUpSuccess/index.tsx
  shared/index.ts
  shared/types/src/api/admin/LectureCreatePayloadTypes.ts
  shared/types/src/api/common/BbozzakPayloadTypes.ts
  shared/types/src/api/common/CompanyPayloadTypes.ts
  shared/types/src/api/common/GovernmentPayloadTypes.ts
  shared/types/src/api/common/LectureListOptionsTypes.ts
  shared/types/src/api/common/SignUpCommonPayloadTypes.ts
  shared/types/src/api/common/StudentPayloadTypes.ts
  shared/types/src/api/common/index.ts
Labels: ⚡️ Simple, ✨ Feature

#180 [Common] 강의 아이템 스타일 수정
  shared/api/admin/src/index.ts
  shared/common/src/atoms/index.ts
  shared/common/src/components/LectureItem/index.tsx
  shared/common/src/components/LectureItem/style.ts
  shared/common/src/pages/lecture/page/index.tsx
  shared/types/src/api/common/LectureDetailResponseTypes.ts
  shared/types/src/api/common/LectureItemType.ts
  shared/types/src/common/FilterListTypes.ts
Labels: 🎨 Publishing

#179 [Common] 학생 강의 수강 여부 확인 컴포넌트 제작
  shared/common/src/components/ApplyItem/index.stories.tsx
  shared/common/src/components/CompleteLectureItem/index.stories.tsx
  shared/common/src/components/CompleteLectureItem/index.tsx
  shared/common/src/components/CompleteLectureItem/style.ts
  shared/common/src/components/index.ts
  shared/common/src/pages/club/student/index.tsx
Labels: ✨ Feature, 🎨 Publishing

#181 [Inside, Outside, Common] 강의 생성 모달 변경사항 적용
  packages/inside/src/app/main/lecture/create/page.tsx
  packages/outside/src/app/main/lecture/create/page.tsx
  shared/api/admin/src/hooks/admin/index.ts
  shared/api/common/src/hooks/lecture/index.ts
  shared/api/common/src/hooks/lecture/useGetDepartments.ts
  shared/api/common/src/hooks/lecture/useGetDivisions.ts
  shared/api/common/src/hooks/lecture/useGetInstructors.ts
  shared/api/common/src/hooks/lecture/useGetLines.ts
  shared/api/common/src/hooks/lecture/usePostLecture.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/api/common/src/libs/urlController.ts
  shared/common/src/assets/svg/CautionIcon.tsx
  shared/common/src/assets/svg/index.ts
  shared/common/src/atoms/index.ts
  shared/common/src/modals/LectureSettingModal/LectureApplyTime/index.tsx
  shared/common/src/modals/LectureSettingModal/LectureApplyTime/style.ts
  shared/common/src/modals/LectureSettingModal/LectureCreditSelect/index.tsx
  shared/common/src/modals/LectureSettingModal/LectureEnrollmentDates/index.tsx
  shared/common/src/modals/LectureSettingModal/LectureEnrollmentDates/style.ts
  shared/common/src/modals/LectureSettingModal/LectureMaxInput/index.tsx
  shared/common/src/modals/LectureSettingModal/LectureMaxInput/style.ts
  shared/common/src/modals/LectureSettingModal/LectureSemesterSelect/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchDepartment/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchDivision/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchInstructor/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchLectureType/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchLine/index.tsx
  shared/common/src/modals/LectureSettingModal/index.stories.tsx
  shared/common/src/modals/LectureSettingModal/index.tsx
  shared/common/src/modals/LectureSettingModal/style.ts
  shared/common/src/modals/index.ts
  shared/common/src/pages/index.ts
  shared/common/src/pages/lecture/create/index.tsx
  shared/common/src/pages/lecture/create/style.ts
  shared/common/src/pages/lecture/index.ts
  shared/types/src/api/admin/LinePayloadTypes.ts
  shared/types/src/api/admin/index.ts
  shared/types/src/api/common/DepartmentsResponseTypes.ts
  shared/types/src/api/common/DivisionsResponseTypes.ts
  shared/types/src/api/common/InstructorsResponseTypes.ts
  shared/types/src/api/common/LectureCreatePayloadTypes.ts
  shared/types/src/api/common/LectureDetailResponseTypes.ts
  shared/types/src/api/common/LectureItemType.ts
  shared/types/src/api/common/LectureListOptionsTypes.ts
  shared/types/src/api/common/LinesPayloadTypes.ts
  shared/types/src/api/common/LinesResponseTypes.ts
  shared/types/src/api/common/index.ts
Labels: ♻️ Refactor, ✨ Feature

#182 [Common] 강의 상세 날짜 포맷
  shared/common/src/pages/lecture/detail/index.tsx
Labels: ⚡️ Simple
