Repository School-of-Company/Bitgouel-Frontend, pull requests merged in 2024-08, with the labels that each got.

#340 [Common] ApplyDisplayInfo 컴포넌트 추가
  shared/common/src/components/ListComponents/LectureApplyList/ApplyDisplayInfo/index.tsx
  shared/common/src/components/ListComponents/LectureApplyList/ApplyDisplayInfo/style.ts
  shared/common/src/pages/lecture/apply/index.tsx
  shared/common/src/pages/lecture/apply/style.ts
Labels: 🎨 Publishing

#342 [Api, Common, Types] 강의 이수 명단 제작
  shared/api/common/src/hooks/lecture/usePatchApplyComplete.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/api/common/src/libs/urlController.ts
  shared/common/src/assets/svg/CompleteIcon.tsx
  shared/common/src/assets/svg/index.ts
  shared/common/src/components/LectureApplyItem/index.stories.tsx
  shared/common/src/components/LectureApplyItem/index.tsx
  shared/common/src/components/LectureApplyItem/style.ts
  shared/common/src/components/ListComponents/LectureApplyList/ApplyDisplayInfo/style.ts
  shared/common/src/components/ListComponents/LectureApplyList/index.tsx
  shared/common/src/components/ListComponents/LectureApplyList/style.ts
  shared/common/src/components/index.ts
  shared/types/src/common/AppropriationModalProps.ts
  shared/types/src/common/LectureApplyItemProps.ts
  shared/types/src/common/index.ts
Labels: ♻️ Refactor, ⚡️performance, 🎨 Publishing

#344 [Api, Common] 회원가입 오류 수정
  shared/api/common/src/hooks/club/index.ts
  shared/api/common/src/hooks/club/useGetClubNameList.ts
  shared/api/common/src/hooks/index.ts
  shared/api/common/src/hooks/school/useGetSchoolNameList.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/api/common/src/libs/urlController.ts
  shared/common/src/hooks/useSignUp.tsx
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpButtonContainer/index.tsx
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpButtonContainer/style.ts
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpScrollContainer/index.tsx
Labels: 1️⃣ Priority: High, 🐞 Bug

#346 [Admin, Type] 관리자 동아리 페이지에서 학교 이름 표시
  packages/outside/src/PageContainer/Club/ClubPage/index.tsx
  shared/types/src/api/client/SchoolClubListResponseTypes.ts
Labels: ⚡️ Simple

#348 [Admin] 강의 수정 시 학점 조건 추가
  shared/common/src/pages/lecture/write/index.tsx
Labels: ⚡️ Simple, 🐞 Bug

#350 [Admin] 관리자 페이지의 직업 행 수정
  packages/outside/src/PageContainer/Admin/UserListPage/index.tsx
  packages/outside/src/components/AdminDisplayInfo/NewDisplayInfo/index.tsx
  packages/outside/src/components/AdminDisplayInfo/UserDisplayInfo/index.tsx
  packages/outside/src/components/AdminDisplayInfo/WithdrawDisplayInfo/index.tsx
  packages/outside/src/components/AdminListComponent/NewUserList/index.tsx
  packages/outside/src/components/AdminListComponent/WithdrawUserList/index.tsx
Labels: ⚡️ Simple, 🎨 Publishing

#352 [Common] QueriClient 기본 설정 추가
  shared/common/src/layouts/GlobalLayout.tsx
Labels: ⚙ Setting, ⚡️performance

#353 [Common] 분야 스크롤 모달 스타일 수정
  shared/common/src/components/FieldScroll/index.tsx
  shared/common/src/components/FieldScroll/style.ts
Labels: ♻️ Refactor, 🎨 Publishing

#355 [Common] 파일 연속 업로드 오류
  shared/common/src/components/MyContent/index.tsx
  shared/common/src/pages/my/index.tsx
Labels: 1️⃣ Priority: High, ⚡️ Simple, 🐞 Bug

#356 [Common] 메인 페이지 퍼블리싱을 임시 편성합니다
  shared/common/src/components/ClubListContents/ClubListContents1/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents2/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents3/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents4/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents5/index.tsx
Labels: 🎨 Publishing

#358 [Common] 필터링 검색 UI 오류 해결
  shared/common/src/components/FilterSearchComponent/style.ts
Labels: 🎨 Publishing

#360 [Common] 강의 신청자 상세 조회 모달 퍼블리싱
  shared/common/src/components/CommonCheckBox/index.tsx
  shared/common/src/components/CompoundListItemComponent/index.tsx
  shared/common/src/components/CompoundListItemComponent/style.ts
  shared/common/src/components/ListComponents/LectureApplyList/index.tsx
  shared/common/src/modals/ApplyDetailModal/index.stories.tsx
  shared/common/src/modals/ApplyDetailModal/index.tsx
  shared/common/src/modals/ApplyDetailModal/style.ts
  shared/common/src/modals/index.ts
Labels: 🎨 Publishing

#362 [Api, Common] 강의 상세 조회 모달 api 연결
  shared/api/common/src/hooks/lecture/index.ts
  shared/api/common/src/hooks/lecture/useGetLectureApplyDetail.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/api/common/src/libs/urlController.ts
  shared/common/src/components/ListComponents/LectureApplyList/ApplyDisplayInfo/index.tsx
  shared/common/src/components/ListComponents/LectureApplyList/index.tsx
  shared/common/src/modals/ApplyDetailModal/index.tsx
Labels: ✨ Feature

#364 [Admin] 학교 정보 수정 모달 제작, 학교 로고 리퍼블리싱
  packages/outside/src/PageContainer/Admin/SchoolPage/index.tsx
  packages/outside/src/components/AdminItemComponent/CompanyItem/index.tsx
  packages/outside/src/components/AdminItemComponent/SchoolItem/index.tsx
  packages/outside/src/components/AdminListComponent/SchoolList/index.tsx
  packages/outside/src/components/LogoButton/index.tsx
  packages/outside/src/components/SchoolInputItem/style.ts
  packages/outside/src/modals/CreateModal/CreateSchoolModal/index.stories.tsx
  packages/outside/src/modals/CreateModal/CreateSchoolModal/index.tsx
  packages/outside/src/modals/CreateModal/SchoolModal/SearchSchoolType/index.tsx
  packages/outside/src/modals/CreateModal/SchoolModal/index.stories.tsx
  packages/outside/src/modals/CreateModal/SchoolModal/index.tsx
  packages/outside/src/modals/CreateModal/SchoolModal/style.ts
  packages/outside/src/modals/CreateModal/index.ts
  packages/outside/src/modals/CreateModal/style.ts
  shared/api/admin/src/hooks/school/usePatchSchool.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/api/common/src/libs/urlController.ts
  shared/common/src/assets/svg/LogoImagePlus.tsx
  shared/common/src/assets/svg/index.ts
  shared/common/src/components/CompoundListItemComponent/index.tsx
  shared/common/src/modals/LectureSettingModal/LecturePlaceInput/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchInstructor/index.tsx
  shared/types/src/api/admin/RegistrationTypes.ts
  shared/types/src/api/admin/SchoolListResponseTypes.ts
Labels: ♻️ Refactor, ⚡️performance, ✨ Feature, 🎨 Publishing

#366 [Api, Common] 강의 신청자 명단 엑셀 파일 다운로드 오류 해결
  shared/api/admin/src/hooks/lecture/useGetLectureExcel.ts
  shared/common/src/pages/lecture/page/index.tsx
  shared/common/src/utils/excelDownload.ts
Labels: ♻️ Refactor, ⚡️performance

#368 [Common] 강의 이수 여부와 이수 날짜 표시
  shared/common/src/modals/ApplyDetailModal/index.tsx
  shared/common/src/modals/ApplyDetailModal/style.ts
Labels: 🎨 Publishing

#370 [Common] 강의 수정 에러 수정
  shared/common/src/pages/lecture/write/index.tsx
Labels: 1️⃣ Priority: High, ⚡️ Simple, ⚡️performance, 🐞 Bug

#373 [Common] 강의 수정 버튼 활성화 조건 수정
  shared/common/src/pages/lecture/write/index.tsx
Labels: 3️⃣ Priority: Low, ⚡️ Simple, 🐞 Bug

#375 [Common] 강의 로딩, 목록 없을 시 UI 처리
  shared/common/src/components/LectureItem/style.ts
  shared/common/src/components/ListComponents/LectureList/index.tsx
  shared/common/src/pages/lecture/page/index.tsx
  shared/common/src/utils/excelDownload.ts
Labels: ⚡️performance

#379 [Common] 강의 개설 모달 버튼 글자 수정
  shared/common/src/pages/lecture/write/index.tsx
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#382 [Common] 강의 학기가 없을 시 UI 처리
  shared/common/src/components/LectureItem/index.tsx
  shared/common/src/components/LectureItem/style.ts
Labels: 0️⃣ Priority: Critical, 🎨 Publishing

#383 [Common] 엑셀 일괄 삽입 시 응답 핸들링 추가
  shared/common/src/pages/my/index.tsx
Labels: 0️⃣ Priority: Critical, ⚡️performance

#385 [Admin] 동아리 추가 모달 질문 수정
  packages/outside/src/components/AdminItemComponent/SchoolItem/index.tsx
  shared/types/src/common/AppropriationModalProps.ts
Labels: 1️⃣ Priority: High, ⚡️ Simple

#391 [Common] 강의 이수, 신청 명단 페이지에 버튼 추가
  shared/common/src/assets/svg/ListDocumentIcon.tsx
  shared/common/src/assets/svg/ReadingGlassesIcon.tsx
  shared/common/src/assets/svg/index.ts
  shared/common/src/pages/lecture/apply/index.tsx
  shared/common/src/pages/lecture/complete/index.tsx
Labels: 3️⃣ Priority: Low, 🎨 Publishing

#393 [Api, Common] 엑셀 다운로드 비동기 처리
  shared/api/admin/src/hooks/lecture/useGetLectureExcel.ts
  shared/common/src/pages/lecture/page/index.tsx
  shared/common/src/utils/excelDownload.ts
Labels: 2️⃣ Priority: Medium, ⚡️performance, 🐞 Bug

#395 [Common] 로그인 버튼 태그 타입 변경
  shared/common/src/components/Auth/Login/LoginForm/LoginButton/index.tsx
  shared/common/src/components/Auth/Login/LoginForm/index.tsx
Labels: 3️⃣ Priority: Low, ⚡️performance

#397 [Common] 강의 이수, 신청 명단 캐시 무효화
  shared/common/src/components/ListComponents/LectureApply/LectureApplyList/index.tsx
  shared/common/src/components/ListComponents/LectureApply/LectureCompleteList/index.tsx
Labels: 1️⃣ Priority: High, ⚡️performance, 🐞 Bug

#400 [Api, Common] 강의 신청자 명단 파일의 위치와 이름을 사용자가 지정할 수 있도록 변경
  shared/api/admin/src/hooks/lecture/useGetLectureExcel.ts
  shared/common/src/pages/lecture/page/index.tsx
  shared/common/src/utils/excelDownload.ts
Labels: 3️⃣ Priority: Low, ⚡️performance

#401 Deploy
  shared/api/admin/src/hooks/lecture/useGetLectureExcel.ts
  shared/common/src/pages/lecture/page/index.tsx
  shared/common/src/utils/excelDownload.ts
Labels: 🌏 Deploy

#404 [Common] 학생 정보 일괄 삽입의 onError에서 구조 분해 할당하는 요소 수정
  shared/common/src/pages/my/index.tsx
Labels: 1️⃣ Priority: High, ⚡️ Simple, 🐞 Bug

#408 [Admin] 동아리 리스트, 나의 정보 불러오기 API 오류 해결
  shared/api/client/src/hooks/club/useGetClubDetail.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/common/src/pages/club/detail/index.tsx
  shared/types/src/api/client/ClubDetailResponseTypes.ts
Labels: 0️⃣ Priority: Critical, 🐞 Bug, 📝 Docs
