Repository School-of-Company/Bitgouel-Frontend, pull requests merged in 2024-02, with the labels that each got.

#121 [Inside] 강의 상세 페이지 버튼 조건 추가
  packages/inside/src/PageContainer/Lecture/LectureDetailPage/index.tsx
  packages/inside/src/PageContainer/Lecture/LectureDetailPage/style.ts
  shared/types/src/api/common/LectureItemType.ts
Labels: ⚡️performance

#124 [Inside, Outside, Common] 권한 가져오는 로직 수정
  packages/inside/src/PageContainer/Lecture/LectureDetailPage/index.tsx
  packages/inside/src/PageContainer/Lecture/LecturePage/index.tsx
  packages/inside/src/PageContainer/Post/NotificationListPage/index.tsx
  packages/inside/src/PageContainer/Post/NotificationListPage/style.ts
  packages/inside/src/PageContainer/Post/index.ts
  packages/inside/src/PageContainer/index.ts
  packages/inside/src/app/main/club/[clubId]/student/[studentId]/page.tsx
  packages/inside/src/app/main/post/notice/[noticeId]/page.tsx
  packages/inside/src/app/main/post/notice/page.tsx
  packages/inside/src/app/main/post/notification/page.tsx
  packages/outside/src/PageContainer/Lecture/LecturePage/index.tsx
  packages/outside/src/PageContainer/Post/NoticeCreatePage/index.tsx
  packages/outside/src/PageContainer/Post/NoticeCreatePage/style.ts
  packages/outside/src/PageContainer/Post/NotificationListPage/index.tsx
  packages/outside/src/PageContainer/Post/index.ts
  packages/outside/src/app/main/post/notice/[noticeId]/page.tsx
  packages/outside/src/app/main/post/notice/create/page.tsx
  packages/outside/src/app/main/post/notice/page.tsx
  packages/outside/src/app/main/post/notification/create/page.tsx
  packages/outside/src/app/main/post/notification/page.tsx
  shared/api/common/src/hooks/auth/usePostLogin.ts
  shared/api/common/src/libs/api/TokenManager.ts
  shared/api/common/src/libs/token.ts
  shared/common/src/components/ClubListContents/ClubListContents1/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents2/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents3/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents4/index.tsx
  shared/common/src/components/ClubListContents/ClubListContents5/index.tsx
  shared/common/src/components/CompanyListContents/CompanyListContents1/index.tsx
  shared/common/src/components/CompanyListContents/CompanyListContents2/index.tsx
  shared/common/src/components/CompanyListContents/CompanyListContents3/index.tsx
  shared/common/src/components/CompanyListContents/CompanyListContents4/index.tsx
  shared/common/src/components/CompanyListContents/CompanyListContents5/index.tsx
  shared/common/src/components/Header/index.tsx
  shared/common/src/components/PostItem/index.tsx
  shared/common/src/pages/index.ts
  shared/common/src/pages/inquiry/detail/index.tsx
  shared/common/src/pages/inquiry/page/index.tsx
  shared/common/src/pages/post/detail/index.tsx
  shared/common/src/pages/post/index.ts
  shared/common/src/pages/post/notice/detail/index.tsx
  shared/common/src/pages/post/notice/detail/style.ts
  shared/common/src/pages/post/notice/index.ts
  shared/common/src/pages/post/notice/modify/index.tsx
  shared/common/src/pages/post/notice/modify/style.ts
  shared/common/src/pages/post/notice/page/index.tsx
  shared/common/src/pages/post/notice/page/style.ts
  shared/common/src/pages/post/page/index.tsx
  shared/types/src/api/common/TokensTypes.ts
Labels: ⚡️performance

#125 [Common] svg 컴포넌트에 props 추가
  packages/outside/src/modals/SchoolFilterModal/index.tsx
  shared/common/src/assets/svg/CalendarIcon.tsx
  shared/common/src/assets/svg/CancelIcon.tsx
  shared/common/src/assets/svg/Chevron.tsx
  shared/common/src/assets/svg/Filter.tsx
  shared/common/src/assets/svg/Message.tsx
  shared/common/src/assets/svg/Plus.tsx
  shared/common/src/assets/svg/Question.tsx
  shared/common/src/components/Header/index.tsx
  shared/common/src/modals/SelectCalendarTimeModal/index.tsx
  shared/common/src/pages/club/student/index.tsx
  shared/common/src/pages/post/page/index.tsx
Labels: ⚡️ Simple, ⚡️performance

#126 [Common] 헤더 업데이트
  packages/outside/src/PageContainer/Lecture/LectureDetailPage/style.ts
  shared/common/src/components/Header/index.tsx
  shared/common/src/components/Header/style.ts
Labels: ♻️ Refactor, ⚡️ Simple
