Repository School-of-Company/Bitgouel-Frontend, pull requests merged in 2024-03, with the labels that each got.

#129 [Common] 게시글, 공지사항 api 변경사항 적용
  packages/outside/src/PageContainer/Post/NoticeCreatePage/index.tsx
  shared/common/src/pages/post/create/index.tsx
  shared/common/src/pages/post/notice/page/index.tsx
  shared/common/src/pages/post/page/index.tsx
  shared/types/src/api/common/PostCreatePayloadTypes.ts
  shared/types/src/api/common/PostDetailResponseTypes.ts
Labels: ⚡️ Simple, 🎨 Publishing

#130 [Common] 문의사항 검색창, 필터 추가
  packages/inside/src/app/main/inquiry/page.tsx
  packages/outside/src/app/main/inquiry/page.tsx
  packages/outside/src/modals/LectureSettingModal/style.ts
  shared/api/admin/inquiry/useGetInquiryList.ts
  shared/api/common/src/libs/urlController.ts
  shared/common/src/assets/svg/SearchIcon.tsx
  shared/common/src/assets/svg/index.ts
  shared/common/src/pages/home/index.tsx
  shared/common/src/pages/home/style.ts
  shared/common/src/pages/inquiry/page/index.tsx
  shared/common/src/pages/inquiry/page/style.ts
  shared/common/src/pages/lecture/page/index.tsx
  shared/common/src/pages/post/notice/page/index.tsx
  shared/common/src/pages/post/page/index.tsx
  shared/types/src/api/admin/InquiryListQueryStringTypes.ts
  shared/types/src/api/admin/index.ts
  shared/types/src/api/inside/index.ts
  shared/types/src/common/InquiryFiltersTypes.ts
  shared/types/src/common/index.ts
Labels: ✨ Feature, 🎨 Publishing

#131 [Common, Inside, Outside] 문의사항 관련 파일 위치 수정 및 API 요청 권한 분리 로직 수정
  packages/inside/src/app/main/post/inquiry/[inquiryId]/page.tsx
  packages/inside/src/app/main/post/inquiry/create/page.tsx
  packages/inside/src/app/main/post/inquiry/modify/[inquiryId]/page.tsx
  packages/inside/src/app/main/post/inquiry/page.tsx
  packages/outside/src/app/main/post/inquiry/[inquiryId]/page.tsx
  packages/outside/src/app/main/post/inquiry/page.tsx
  shared/api/admin/inquiry/useDeleteInquiryReject.ts
  shared/api/admin/inquiry/usePostAnswer.ts
  shared/api/common/src/hooks/inquiry/useDeleteInquiry.ts
  shared/api/common/src/hooks/inquiry/usePatchMyInquiry.ts
  shared/api/common/src/hooks/inquiry/usePostInquiry.ts
  shared/common/src/components/Header/index.tsx
  shared/common/src/components/InquiryItem/index.tsx
  shared/common/src/pages/home/index.tsx
  shared/common/src/pages/inquiry/detail/index.tsx
  shared/common/src/pages/inquiry/page/index.tsx
  shared/common/src/pages/post/notice/page/index.tsx
  shared/common/src/pages/post/page/index.tsx
Labels: ⚡️performance, 🎨 Publishing

#132 [Common] 문의 사항 답변 완료
  shared/api/common/src/libs/urlController.ts
  shared/common/src/modals/InquiryAnswerModal/index.tsx
  shared/common/src/modals/InquiryAnswerModal/style.ts
  shared/common/src/modals/index.ts
  shared/common/src/pages/inquiry/detail/index.tsx
  shared/common/src/pages/inquiry/detail/style.ts
  shared/common/src/pages/inquiry/page/index.tsx
  shared/types/src/common/AppropriationModalProps.ts
Labels: ✨ Feature, 🎨 Publishing

#138 [Outside, Common] 강의 생성 모달 검색 요소들 완성
  packages/outside/src/modals/LectureSettingModal/LectureApplyTime/index.tsx
  packages/outside/src/modals/LectureSettingModal/LectureApplyTime/style.ts
  packages/outside/src/modals/LectureSettingModal/SearchDepartment/index.tsx
  packages/outside/src/modals/LectureSettingModal/SearchLine/index.tsx
  packages/outside/src/modals/LectureSettingModal/SearchProfessor/index.tsx
  packages/outside/src/modals/LectureSettingModal/index.tsx
  shared/api/admin/admin/useGetDepartment.ts
  shared/api/common/src/libs/urlController.ts
  shared/common/src/assets/svg/InputCancel.tsx
  shared/common/src/assets/svg/SearchIcon.tsx
  shared/common/src/assets/svg/index.ts
  shared/common/src/components/LectureItem/index.stories.tsx
  shared/common/src/components/LectureItem/index.tsx
  shared/types/src/api/common/LectureItemType.ts
Labels: ⚡️performance, 🎨 Publishing

#139 Add lecture apply time
  packages/outside/src/modals/LectureSettingModal/LectureApplyTime/index.tsx
  packages/outside/src/modals/LectureSettingModal/LectureApplyTime/style.ts
  packages/outside/src/modals/LectureSettingModal/LectureEnrollmentDates/index.tsx
  packages/outside/src/modals/LectureSettingModal/LectureEnrollmentDates/style.ts
  packages/outside/src/modals/LectureSettingModal/index.tsx
  packages/outside/src/modals/LectureSettingModal/style.ts
Labels: 🎨 Publishing

#140 [Common, Outside] 강의 수강일 입력 완성
  packages/outside/src/modals/LectureSettingModal/LectureApplyTime/index.tsx
  packages/outside/src/modals/LectureSettingModal/LectureEnrollmentDates/index.tsx
  packages/outside/src/modals/LectureSettingModal/LectureEnrollmentDates/style.ts
  packages/outside/src/modals/LectureSettingModal/LectureMaxInput/style.ts
  packages/outside/src/modals/LectureSettingModal/SearchProfessor/index.tsx
  packages/outside/src/modals/LectureSettingModal/index.tsx
  packages/outside/src/modals/LectureSettingModal/style.ts
  pnpm-lock.yaml
  shared/common/src/assets/svg/InputCancel.tsx
  shared/common/src/assets/svg/SearchIcon.tsx
Labels: ✨ Feature, 🎨 Publishing

#142 fix(package absolute path issue, use client issue)
  packages/inside/src/app/main/club/[clubId]/student/[studentId]/activity/[activityId]/page.tsx
  packages/inside/src/app/main/club/[clubId]/student/[studentId]/activity/create/page.tsx
  packages/inside/src/app/main/club/[clubId]/student/[studentId]/activity/page.tsx
  packages/inside/src/app/main/club/[clubId]/student/[studentId]/page.tsx
  packages/inside/src/app/main/club/page.tsx
  pnpm-lock.yaml
  shared/api/common/src/libs/urlController.ts
  shared/common/package.json
  shared/common/src/atoms/index.ts
  shared/common/src/components/ActivityItem/index.tsx
  shared/common/src/pages/activity/detail/index.tsx
  shared/common/src/pages/activity/list/index.tsx
  shared/common/src/pages/club/detail/index.tsx
  shared/common/src/pages/club/student/index.tsx
  shared/common/src/pages/home/index.tsx
  shared/common/src/pages/inquiry/detail/index.tsx
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, 🐞 Bug

#143 [Common] 학생 활동 상세보기
  packages/inside/src/PageContainer/Club/ActivityDetailPage/index.tsx
  packages/inside/src/PageContainer/Club/index.ts
  packages/inside/src/app/main/club/[clubId]/student/[studentId]/activity/create/page.tsx
  packages/inside/src/app/main/club/[clubId]/student/[studentId]/activity/page.tsx
  packages/inside/src/app/main/club/[clubId]/student/[studentId]/page.tsx
  packages/inside/src/app/main/club/page.tsx
  packages/outside/src/app/main/club/[clubId]/student/[studentId]/activity/[activityId]/.gitkeep
  packages/outside/src/app/main/club/[clubId]/student/[studentId]/activity/[activityId]/page.tsx
  packages/outside/src/app/main/club/[clubId]/student/[studentId]/activity/page.tsx
  pnpm-lock.yaml
  shared/api/common/src/libs/urlController.ts
  shared/common/package.json
  shared/common/src/atoms/index.ts
  shared/common/src/components/ActivityItem/index.tsx
  shared/common/src/modals/InquiryAnswerModal/index.tsx
  shared/common/src/pages/activity/detail/index.tsx
  shared/common/src/pages/activity/detail/style.ts
  shared/common/src/pages/activity/list/index.tsx
  shared/common/src/pages/club/detail/index.tsx
  shared/common/src/pages/club/index.ts
  shared/common/src/pages/club/student/index.tsx
  shared/common/src/pages/home/index.tsx
  shared/common/src/pages/index.ts
  shared/common/src/pages/inquiry/detail/index.tsx
  shared/index.ts
  shared/types/src/common/ActivityDetailProps.ts
  shared/types/src/common/index.ts
Labels: 1️⃣ Priority: High, ✨ Feature

#141 [Common, Outside] 강의 개설 완료
  packages/outside/src/PageContainer/Lecture/LectureCreatePage/index.tsx
  packages/outside/src/PageContainer/Lecture/LectureCreatePage/style.ts
  packages/outside/src/modals/LectureSettingModal/LectureApplyTime/index.tsx
  packages/outside/src/modals/LectureSettingModal/LectureCreditSelect/index.tsx
  packages/outside/src/modals/LectureSettingModal/LectureDivisonSelect/index.tsx
  packages/outside/src/modals/LectureSettingModal/LectureEnrollmentDates/index.tsx
  packages/outside/src/modals/LectureSettingModal/LectureTypeSelect/index.tsx
  packages/outside/src/modals/LectureSettingModal/SearchLine/index.tsx
  packages/outside/src/modals/LectureSettingModal/index.tsx
  shared/common/src/atoms/index.ts
Labels: ✨ Feature, 🎨 Publishing

#144 [Inside] 학생 활동 수정하기 기능
  packages/inside/src/PageContainer/Club/ActivityCreatePage/index.tsx
  packages/inside/src/PageContainer/Club/ActivityModifyPage/index.tsx
  packages/inside/src/PageContainer/Club/ActivityModifyPage/style.ts
  packages/inside/src/app/main/club/[clubId]/student/[studentId]/activity/[activityId]/modify/page.tsx
  shared/api/client/src/hooks/activity/usePatchActivityModifyInformation.ts
  shared/api/client/src/hooks/activity/usePostActivityInformation.ts
  shared/common/src/pages/activity/list/index.tsx
  shared/types/src/common/AppropriationModalProps.ts
Labels: 1️⃣ Priority: High, ✨ Feature

#145 [Common, Outside] 강의 상세 페이지 수정
  packages/inside/src/app/main/lecture/[lectureId]/page.tsx
  packages/inside/src/app/main/lecture/page.tsx
  packages/inside/src/modals/LectureApplyModal/index.stories.tsx
  packages/inside/src/modals/LectureApplyModal/index.tsx
  packages/inside/src/modals/LectureApplyModal/style.ts
  packages/inside/src/modals/index.ts
  packages/outside/src/app/main/lecture/[lectureId]/page.tsx
  packages/outside/src/app/main/lecture/create/page.tsx
  packages/outside/src/app/main/lecture/page.tsx
  shared/common/src/components/LectureItem/index.tsx
  shared/common/src/hooks/useModal.tsx
  shared/common/src/pages/lecture/detail/index.tsx
  shared/common/src/pages/lecture/detail/style.ts
  shared/common/src/pages/lecture/page/index.tsx
  shared/types/src/api/common/LectureItemType.ts
  shared/types/src/common/AppropriationModalProps.ts
  shared/types/src/common/CreateModalProps.ts
  shared/types/src/common/index.ts
Labels: ✨ Feature, 🎨 Publishing

#146 [Inside, Admin] 학생 활동 수정, 삭제 권한
  shared/common/src/pages/activity/detail/index.tsx
Labels: 2️⃣ Priority: Medium, ⚡️ Simple, ✨ Feature

#147 [Common, Inside, Outside] 로그인 회원가입 로직 수정
  packages/inside/src/app/auth/signUp/page.tsx
  packages/outside/src/app/auth/signUp/page.tsx
  pnpm-lock.yaml
  shared/api/common/src/hooks/auth/usePostBbozzakSignUp.ts
  shared/api/common/src/hooks/auth/usePostCompanyInstructorSignUp.ts
  shared/api/common/src/hooks/auth/usePostGovernmentSignUp.ts
  shared/api/common/src/hooks/auth/usePostLogin.ts
  shared/api/common/src/hooks/auth/usePostProfessorSignUp.ts
  shared/api/common/src/hooks/auth/usePostStudentSignUp.ts
  shared/api/common/src/hooks/auth/usePostTeacherSignUp.ts
  shared/api/package.json
  shared/common/src/atoms/index.ts
  shared/common/src/pages/login/index.tsx
  shared/common/src/pages/signUp/Pagination/SignUpButtonContainer/index.tsx
  shared/common/src/pages/signUp/Pagination/SignUpPage1/index.tsx
  shared/common/src/pages/signUp/Pagination/SignUpPage1/style.ts
  shared/common/src/pages/signUp/Pagination/SignUpPage2/index.tsx
  shared/common/src/pages/signUp/Pagination/SignUpPage3/index.tsx
  shared/common/src/pages/signUp/Pagination/SignUpPage3/style.ts
  shared/common/src/pages/signUp/Pagination/index.ts
  shared/common/src/pages/signUp/index.tsx
  shared/types/src/common/SignUpObjTypes.ts
  shared/types/src/common/index.ts
Labels: ♻️ Refactor, ⚡️performance

#148 [Common, Inside, Outside] 동아리 데이터 불러오는 조건 수정
  packages/inside/src/app/main/club/[clubId]/page.tsx
  packages/inside/src/app/main/club/[clubId]/student/[studentId]/page.tsx
  packages/inside/src/app/main/club/page.tsx
  packages/inside/src/app/main/post/modify/[postId]/page.tsx
  packages/outside/src/app/main/club/[clubId]/page.tsx
  packages/outside/src/app/main/club/[clubId]/student/[studentId]/page.tsx
  packages/outside/src/app/main/club/page.tsx
  shared/common/src/components/CertificateItem/index.tsx
  shared/common/src/components/index.ts
  shared/common/src/pages/club/detail/index.tsx
  shared/common/src/pages/club/detail/style.ts
  shared/common/src/pages/club/student/index.tsx
Labels: ⚡️performance

#149 [Common] 시간 변환 관련 util 함수들 정의
  shared/common/src/index.ts
  shared/common/src/utils/date.ts
  shared/common/src/utils/index.ts
Labels: ✨ Feature

#151 [Common, Inside, Outside] 문의 사항 작성 페이지 통합
  packages/inside/src/PageContainer/Inquiry/InquiryCreatePage/index.tsx
  packages/inside/src/PageContainer/Inquiry/InquiryModifyPage/index.tsx
  packages/inside/src/PageContainer/Inquiry/InquiryModifyPage/style.ts
  packages/inside/src/PageContainer/Inquiry/InquiryWritePage/index.tsx
  packages/inside/src/PageContainer/Inquiry/InquiryWritePage/style.ts
  packages/inside/src/PageContainer/Inquiry/index.ts
  packages/inside/src/app/main/post/inquiry/[inquiryId]/modify/page.tsx
  packages/inside/src/app/main/post/inquiry/create/page.tsx
  packages/inside/src/app/main/post/inquiry/modify/[inquiryId]/page.tsx
  packages/outside/src/app/main/post/inquiry/[inquiryId]/page.tsx
  shared/common/src/pages/inquiry/detail/index.tsx
  shared/common/src/pages/inquiry/page/index.tsx
  shared/common/src/utils/date.ts
  shared/types/src/api/common/InquiryDetailResponseTypes.ts
Labels: ⚡️performance

#152 [Common, Inside, Outside] 비밀번호 찾기, 변경 기능 추가
  packages/inside/src/app/auth/find/page.tsx
  packages/inside/src/app/auth/login/page.tsx
  packages/inside/src/app/main/club/[clubId]/page.tsx
  packages/inside/src/app/main/my/page.tsx
  packages/inside/src/app/main/post/[postId]/page.tsx
  packages/inside/src/app/main/post/create/page.tsx
  packages/inside/src/app/main/post/inquiry/[inquiryId]/page.tsx
  packages/inside/src/app/main/post/inquiry/page.tsx
  packages/inside/src/app/main/post/modify/[postId]/page.tsx
  packages/inside/src/app/main/post/notice/[noticeId]/page.tsx
  packages/inside/src/app/main/post/notice/page.tsx
  packages/inside/src/app/main/post/page.tsx
  packages/inside/src/app/page.tsx
  packages/outside/src/app/auth/find/page.tsx
  packages/outside/src/app/auth/login/page.tsx
  packages/outside/src/app/main/club/[clubId]/page.tsx
  packages/outside/src/app/main/club/[clubId]/student/[studentId]/page.tsx
  packages/outside/src/app/main/my/page.tsx
  packages/outside/src/app/main/post/[postId]/page.tsx
  packages/outside/src/app/main/post/create/page.tsx
  packages/outside/src/app/main/post/inquiry/page.tsx
  packages/outside/src/app/main/post/modify/[postId]/page.tsx
  packages/outside/src/app/main/post/notice/[noticeId]/page.tsx
  packages/outside/src/app/main/post/notice/page.tsx
  packages/outside/src/app/main/post/page.tsx
  packages/outside/src/app/page.tsx
  shared/api/common/src/hooks/auth/useDeleteLogout.ts
  shared/api/common/src/hooks/email/index.ts
  shared/api/common/src/hooks/email/useGetEmail.ts
  shared/api/common/src/hooks/email/usePostEmail.ts
  shared/api/common/src/hooks/index.ts
  shared/api/common/src/hooks/my/usePatchPassword.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/api/common/src/libs/urlController.ts
  shared/common/src/atoms/index.ts
  shared/common/src/components/Header/index.tsx
  shared/common/src/components/ValueInput/index.tsx
  shared/common/src/modals/ChangePwModal/index.stories.tsx
  shared/common/src/modals/ChangePwModal/index.tsx
  shared/common/src/modals/ChangePwModal/style.ts
  shared/common/src/modals/index.ts
  shared/common/src/pages/find/Pagination/ChangePasswordSuccess/index.tsx
  shared/common/src/pages/find/Pagination/ChangePasswordSuccess/style.ts
  shared/common/src/pages/find/Pagination/EmailCheck/index.tsx
  shared/common/src/pages/find/Pagination/EmailCheck/style.ts
  shared/common/src/pages/find/Pagination/EmailValid/index.tsx
  shared/common/src/pages/find/Pagination/EmailValid/style.ts
  shared/common/src/pages/find/Pagination/NewPassword/index.tsx
  shared/common/src/pages/find/Pagination/NewPassword/style.ts
  shared/common/src/pages/find/Pagination/index.ts
  shared/common/src/pages/find/index.tsx
  shared/common/src/pages/find/style.ts
  shared/common/src/pages/index.ts
  shared/common/src/pages/my/index.tsx
  shared/types/src/common/EmailProps.ts
  shared/types/src/common/index.ts
Labels: ✨ Feature, 🎨 Publishing

#154 [Common, Inside, Outside] FAQ 기능 퍼블리싱
  shared/common/src/components/FAQAnswerItem/index.stories.tsx
  shared/common/src/components/FAQAnswerItem/index.tsx
  shared/common/src/components/FAQAnswerItem/style.ts
  shared/common/src/components/FAQItem/index.stories.tsx
  shared/common/src/components/FAQItem/index.tsx
  shared/common/src/components/FAQItem/style.ts
  shared/common/src/components/FAQSection/index.stories.tsx
  shared/common/src/components/FAQSection/index.tsx
  shared/common/src/components/FAQSection/style.ts
  shared/common/src/components/Header/index.tsx
  shared/common/src/components/Sequence/index.tsx
  shared/common/src/components/index.ts
  shared/common/src/pages/home/index.tsx
  shared/common/src/pages/home/style.ts
  shared/types/src/common/FAQProps.ts
  shared/types/src/common/index.ts
Labels: 🎨 Publishing

#155 [Inside, Common] 학생 페이지 자격증 수정, 변경 사항
  packages/inside/src/PageContainer/Club/ActivityModifyPage/index.tsx
  packages/inside/src/app/main/club/[clubId]/page.tsx
  packages/inside/src/app/main/club/page.tsx
  shared/api/client/src/hooks/certificate/usePostCertificate.ts
  shared/api/common/src/libs/urlController.ts
  shared/common/src/components/CertificateItem/index.tsx
  shared/common/src/pages/activity/list/index.tsx
  shared/common/src/pages/club/detail/index.tsx
  shared/common/src/pages/club/student/index.tsx
  shared/types/src/api/client/ClubDetailResponseTypes.ts
  shared/types/src/api/common/CertificateProps.ts
  shared/types/src/api/common/index.ts
  shared/types/src/api/index.ts
Labels: ♻️ Refactor, ✨ Feature

#156 [All, Admin] FAQ 리스트 조회, 추가하기
  shared/api/admin/faq/index.ts
  shared/api/admin/faq/useGetListQuestions.ts
  shared/api/admin/faq/usePostQuestion.ts
  shared/api/admin/index.ts
  shared/api/common/src/libs/api/instance.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/api/common/src/libs/urlController.ts
  shared/common/src/components/FAQAnswerItem/index.tsx
  shared/common/src/components/FAQItem/index.tsx
  shared/common/src/components/FAQSection/index.tsx
  shared/types/src/api/admin/FAQListQuestionsTypes.ts
  shared/types/src/api/admin/index.ts
  shared/types/src/common/FAQProps.ts
  shared/types/src/common/index.ts
Labels: 2️⃣ Priority: Medium, ⚡️performance, ✨ Feature

#157 [Admin, Client, Common] 모든 API import 정리, 절대 경로 지정
  shared/api/admin/admin/useDeleteUserReject.ts
  shared/api/admin/admin/useDeleteUserWithdraw.ts
  shared/api/admin/admin/useGetDepartment.ts
  shared/api/admin/admin/useGetLine.ts
  shared/api/admin/admin/useGetProfessor.ts
  shared/api/admin/admin/useGetUserList.ts
  shared/api/admin/admin/useGetWithDrawUserList.ts
  shared/api/admin/admin/usePatchUserApprove.ts
  shared/api/admin/admin/usePostLecture.ts
  shared/api/admin/club/useGetClubList.ts
  shared/api/admin/club/useGetSchoolClubList.ts
  shared/api/admin/inquiry/useDeleteInquiryReject.ts
  shared/api/admin/inquiry/useGetInquiryList.ts
  shared/api/admin/inquiry/usePostAnswer.ts
  shared/api/client/src/hooks/activity/useDeleteActivityInformationRemove.ts
  shared/api/client/src/hooks/activity/useGetActivityMyselfList.ts
  shared/api/client/src/hooks/activity/usePatchActivityModifyInformation.ts
  shared/api/client/src/hooks/activity/usePostActivityInformation.ts
  shared/api/client/src/hooks/certificate/useGetCertificateList.ts
  shared/api/client/src/hooks/certificate/useGetCertificateListTeacher.ts
  shared/api/client/src/hooks/certificate/usePatchModifyCertificate.ts
  shared/api/client/src/hooks/certificate/usePostCertificate.ts
  shared/api/client/src/hooks/club/useGetClubDetail.ts
  shared/api/client/src/hooks/club/useGetMyClub.ts
  shared/api/client/src/hooks/club/useGetStudentDetail.ts
  shared/api/client/src/hooks/lecture/usePostEnrollment.ts
  shared/api/common/src/hooks/auth/useDeleteWithDraw.ts
  shared/api/common/src/hooks/auth/usePostStudentSignUp.ts
  shared/api/common/src/hooks/auth/usePostTeacherSignUp.ts
  shared/api/common/src/hooks/inquiry/useGetInquiryDetail.ts
  shared/api/common/src/hooks/lecture/useGetDetailLecture.ts
  shared/api/common/src/hooks/my/useGetMy.ts
Labels: ♻️ Refactor, ⚙ Setting
