Repository School-of-Company/Bitgouel-Frontend, pull requests merged in 2024-05, with the labels that each got.

#183 [Common] 강의 수강 여부 리스트
  shared/api/common/src/hooks/lecture/index.ts
  shared/api/common/src/hooks/lecture/useGetCompleteLecture.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/api/common/src/libs/urlController.ts
  shared/common/src/components/CompleteLectureItem/index.tsx
  shared/common/src/components/CompleteLectureItem/style.ts
  shared/common/src/pages/club/student/index.tsx
  shared/common/src/pages/club/student/style.ts
  shared/types/src/common/CompleteLectureTypes.ts
  shared/types/src/common/index.ts
Labels: ✨ Feature, 🎨 Publishing

#186 [Common] 강의 생성에 필수 여부 선택 추가
  shared/api/common/src/hooks/lecture/usePostLecture.ts
  shared/common/src/atoms/index.ts
  shared/common/src/modals/LectureSettingModal/LectureEssentialCompleteSelect/index.tsx
  shared/common/src/modals/LectureSettingModal/LectureMaxInput/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchLectureType/index.tsx
  shared/common/src/modals/LectureSettingModal/index.tsx
  shared/common/src/pages/lecture/create/index.tsx
  shared/types/src/api/common/LectureCreatePayloadTypes.ts
Labels: ✨ Feature

#188 [Common] PrivateRouter 컴포넌트 추가
  shared/api/common/src/hooks/auth/useDeleteLogout.ts
  shared/api/common/src/hooks/auth/useDeleteWithDraw.ts
  shared/api/common/src/libs/api/TokenManager.ts
  shared/api/common/src/libs/api/instance.ts
  shared/common/src/components/PrivateRouter/index.tsx
  shared/common/src/components/index.ts
Labels: ⚡️performance, ✨ Feature

#189 [Inside, Common] PrivateRouter 특정 페이지에 적용
  packages/inside/src/PageContainer/Club/ActivityWritePage/index.tsx
  shared/common/src/pages/activity/detail/index.tsx
  shared/common/src/pages/activity/list/index.tsx
  shared/common/src/pages/lecture/apply/index.tsx
  shared/common/src/pages/lecture/create/index.tsx
  shared/common/src/pages/post/write/index.tsx
Labels: ⚡️performance

#190 [Common, Outside] 필터 모달 새롭게 제작
  packages/outside/src/PageContainer/Admin/UserListPage/index.tsx
  packages/outside/src/PageContainer/Admin/WithdrawUserListPage/index.tsx
  packages/outside/src/PageContainer/Club/ClubPage/index.tsx
  shared/common/src/components/FilterComponent/index.tsx
  shared/common/src/components/FilterComponent/style.ts
  shared/common/src/components/index.ts
  shared/common/src/hooks/index.ts
  shared/common/src/hooks/useDownload.tsx
  shared/common/src/hooks/useFilterSelect.tsx
  shared/common/src/hooks/useModal.ts
  shared/common/src/modals/FilterModal/InputRadio/index.tsx
  shared/common/src/modals/FilterModal/InputRadio/style.ts
  shared/common/src/modals/FilterModal/RadioItem/index.tsx
  shared/common/src/modals/FilterModal/RadioItem/style.ts
  shared/common/src/modals/FilterModal/index.stories.tsx
  shared/common/src/modals/FilterModal/index.tsx
  shared/common/src/modals/FilterModal/style.ts
  shared/common/src/modals/LectureSettingModal/LectureMaxInput/index.tsx
  shared/common/src/modals/LectureSettingModal/SearchLectureType/index.tsx
  shared/common/src/modals/index.ts
  shared/common/src/pages/inquiry/page/index.tsx
  shared/common/src/pages/lecture/create/index.tsx
  shared/common/src/pages/lecture/page/index.tsx
  shared/common/src/pages/lecture/page/style.ts
  shared/types/src/common/FilterListTypes.ts
  shared/types/src/common/index.ts
  shared/types/src/common/onSelectedParameter.ts
Labels: ♻️ Refactor, ⚡️performance, ✨ Feature, 🎨 Publishing

#191 [Common] 엑셀 다운로드 hooks를 util 함수로 수정
  shared/common/src/hooks/index.ts
  shared/common/src/hooks/useDownload.tsx
  shared/common/src/pages/lecture/page/index.tsx
  shared/common/src/utils/excelDownload.ts
  shared/common/src/utils/index.ts
Labels: ♻️ Refactor, ⚡️performance

#192 [Common] 회원가입 제목 분리
  shared/common/src/components/PaginationPages/index.tsx
  shared/common/src/pages/signUp/SignUpPages/SignUpButtonContainer/index.stories.tsx
  shared/common/src/pages/signUp/SignUpPages/SignUpButtonContainer/index.tsx
  shared/common/src/pages/signUp/SignUpPages/SignUpButtonContainer/style.ts
  shared/common/src/pages/signUp/SignUpPages/SignUpPage1/index.tsx
  shared/common/src/pages/signUp/SignUpPages/SignUpPage1/style.ts
  shared/common/src/pages/signUp/SignUpPages/SignUpPage2/index.tsx
  shared/common/src/pages/signUp/SignUpPages/SignUpPage3/index.tsx
  shared/common/src/pages/signUp/SignUpPages/SignUpPage3/style.ts
  shared/common/src/pages/signUp/SignUpPages/SignUpScrollContainer/index.tsx
  shared/common/src/pages/signUp/SignUpPages/SignUpScrollContainer/style.ts
  shared/common/src/pages/signUp/SignUpPages/SignUpSuccess/index.stories.tsx
  shared/common/src/pages/signUp/SignUpPages/SignUpSuccess/index.tsx
  shared/common/src/pages/signUp/SignUpPages/SignUpSuccess/style.ts
  shared/common/src/pages/signUp/SignUpPages/index.ts
  shared/common/src/pages/signUp/SignUpTitle/index.tsx
  shared/common/src/pages/signUp/SignUpTitle/style.ts
  shared/common/src/pages/signUp/index.tsx
  shared/common/src/pages/signUp/style.ts
Labels: ♻️ Refactor, ⚡️ Simple

#193 [Common] 회원가입 공통 스타일 분리 및 폴더 구조 정리
  .prettierrc.json
  shared/common/src/pages/auth/index.ts
  shared/common/src/pages/auth/login/index.stories.tsx
  shared/common/src/pages/auth/login/index.tsx
  shared/common/src/pages/auth/login/style.ts
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpButtonContainer/index.stories.tsx
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpButtonContainer/index.tsx
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpButtonContainer/style.ts
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpPage1/index.tsx
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpPage1/style.ts
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpPage2/index.tsx
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpPage3/index.tsx
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpPage3/style.ts
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpScrollContainer/index.tsx
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpScrollContainer/style.ts
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpSuccess/index.stories.tsx
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpSuccess/index.tsx
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpSuccess/style.ts
  shared/common/src/pages/auth/signUp/SignUpPages/index.ts
  shared/common/src/pages/auth/signUp/SignUpTitle/index.tsx
  shared/common/src/pages/auth/signUp/SignUpTitle/style.ts
  shared/common/src/pages/auth/signUp/index.stories.tsx
  shared/common/src/pages/auth/signUp/index.tsx
  shared/common/src/pages/auth/signUp/style.ts
  shared/common/src/pages/auth/style.ts
  shared/common/src/pages/find/Pagination/ChangePasswordSuccess/index.tsx
  shared/common/src/pages/find/Pagination/ChangePasswordSuccess/style.ts
  shared/common/src/pages/find/index.tsx
  shared/common/src/pages/find/style.ts
  shared/common/src/pages/index.ts
  shared/common/src/pages/signUp/SignUpTitle/index.tsx
Labels: ♻️ Refactor, ⚡️ Simple

#194 [Common] 비밀번호 찾기 페이지 폴더 위치 변경 및 Auth 메뉴 컴포넌트 재사용성 향상
  shared/common/src/pages/auth/AuthFormTitle/index.tsx
  shared/common/src/pages/auth/AuthFormTitle/style.ts
  shared/common/src/pages/auth/AuthTitleMenu/index.tsx
  shared/common/src/pages/auth/AuthTitleMenu/style.ts
  shared/common/src/pages/auth/find/Pagination/ChangePasswordSuccess/index.tsx
  shared/common/src/pages/auth/find/Pagination/ChangePasswordSuccess/style.ts
  shared/common/src/pages/auth/find/Pagination/EmailCheck/index.tsx
  shared/common/src/pages/auth/find/Pagination/EmailCheck/style.ts
  shared/common/src/pages/auth/find/Pagination/EmailValid/index.tsx
  shared/common/src/pages/auth/find/Pagination/EmailValid/style.ts
  shared/common/src/pages/auth/find/Pagination/NewPassword/index.tsx
  shared/common/src/pages/auth/find/Pagination/NewPassword/style.ts
  shared/common/src/pages/auth/find/Pagination/index.ts
  shared/common/src/pages/auth/find/index.tsx
  shared/common/src/pages/auth/find/style.ts
  shared/common/src/pages/auth/index.ts
  shared/common/src/pages/auth/login/index.tsx
  shared/common/src/pages/auth/login/style.ts
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpSuccess/index.tsx
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpSuccess/style.ts
  shared/common/src/pages/auth/signUp/SignUpTitle/index.tsx
  shared/common/src/pages/auth/signUp/index.tsx
  shared/common/src/pages/find/index.tsx
  shared/common/src/pages/index.ts
Labels: ♻️ Refactor, ⚡️performance

#197 [Common, Inside, Outside] 동아리, 게시글 페이지 반응형 스타일링 적용
  packages/inside/src/PageContainer/Club/ActivityWritePage/index.tsx
  packages/inside/src/PageContainer/Club/ActivityWritePage/style.ts
  packages/outside/src/PageContainer/Club/ClubPage/index.tsx
  packages/outside/src/PageContainer/Club/ClubPage/style.ts
  packages/outside/src/PageContainer/Club/SchoolListPage/index.tsx
  packages/outside/src/components/ClubItem/style.ts
  packages/outside/src/components/SchoolFilter/index.tsx
  packages/outside/src/components/SchoolFilter/style.ts
  packages/outside/src/modals/SchoolFilterModal/style.ts
  shared/common/src/components/ActivityItem/style.ts
  shared/common/src/components/CompleteLectureItem/index.tsx
  shared/common/src/components/CompleteLectureItem/style.ts
  shared/common/src/pages/activity/detail/index.tsx
  shared/common/src/pages/activity/detail/style.ts
  shared/common/src/pages/activity/list/index.tsx
  shared/common/src/pages/activity/list/style.ts
  shared/common/src/pages/club/detail/index.tsx
  shared/common/src/pages/club/detail/style.ts
  shared/common/src/pages/club/student/index.tsx
  shared/common/src/pages/club/student/style.ts
  shared/common/src/pages/index.ts
  shared/common/src/pages/lecture/apply/index.tsx
  shared/common/src/pages/lecture/create/index.tsx
  shared/common/src/pages/lecture/detail/index.tsx
  shared/common/src/pages/lecture/page/index.tsx
  shared/common/src/pages/post/detail/index.tsx
  shared/common/src/pages/post/detail/style.ts
  shared/common/src/pages/post/page/index.tsx
  shared/common/src/pages/post/page/style.ts
  shared/common/src/pages/post/write/index.tsx
  shared/common/src/pages/post/write/style.ts
  shared/common/src/pages/styles/index.ts
  shared/common/src/styles/index.ts
  shared/common/src/styles/pageLayout.ts
Labels: ♻️ Refactor, 🎨 Publishing

#198 [Common] Context로 isLoading 공유
  shared/common/src/components/Auth/Login/LoginBottom/index.tsx
  shared/common/src/components/Auth/Login/LoginForm/LoginButtons/index.tsx
  shared/common/src/components/Auth/Login/LoginForm/LoginInput/index.tsx
  shared/common/src/components/Auth/Login/LoginForm/index.tsx
  shared/common/src/contexts/index.ts
  shared/common/src/contexts/login/LoadingStateContext.ts
  shared/common/src/contexts/login/index.ts
  shared/common/src/index.ts
  shared/common/src/pages/auth/login/style.ts
  shared/common/src/pages/my/index.tsx
Labels: ⚡️performance, 🐞 Bug

#201 [Common, Outside] 필터 모달과 custom hooks 수정
  packages/outside/src/PageContainer/Admin/UserListPage/index.tsx
  packages/outside/src/PageContainer/Admin/WithdrawUserListPage/index.tsx
  shared/common/src/hooks/useFilterSelect.tsx
  shared/common/src/pages/inquiry/page/index.tsx
  shared/common/src/pages/lecture/page/index.tsx
Labels: ⚡️performance, 🐞 Bug

#199 [Common, Inside, Outside] 엑셀 파일 업로드 기능 구현
  packages/inside/src/app/main/my/page.tsx
  packages/outside/src/app/main/my/page.tsx
  shared/api/admin/src/hooks/admin/index.ts
  shared/api/admin/src/hooks/admin/usePostExcelUpload.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/api/common/src/libs/urlController.ts
  shared/common/src/pages/lecture/page/index.tsx
  shared/common/src/pages/my/index.tsx
  shared/common/src/pages/my/style.ts
Labels: ✨ Feature, 🎨 Publishing

#202 [Inside, Outside, Common] 관리자 3개 페이지에서 볼 수 있는 정보 추가
  packages/outside/src/PageContainer/Admin/NewUserListPage/index.tsx
  packages/outside/src/PageContainer/Admin/NewUserListPage/style.ts
  packages/outside/src/PageContainer/Admin/UserListPage/index.tsx
  packages/outside/src/PageContainer/Admin/UserListPage/style.ts
  packages/outside/src/PageContainer/Admin/WithdrawUserListPage/index.tsx
  shared/common/src/components/CommonCheckBox/style.ts
  shared/common/src/components/UserItem/index.tsx
  shared/common/src/components/UserItem/style.ts
  shared/common/src/utils/index.ts
  shared/common/src/utils/insertHyphen.ts
  shared/types/src/api/admin/UserListResponseTypes.ts
  shared/types/src/common/UserItemProps.ts
Labels: ✨ Feature, 🎨 Publishing

#203 [Common, Inside, Outside] 공지사항, 문의사항 페이지 반응형 적용 및 관리자 페이지 MainStyle 적용
  packages/inside/src/PageContainer/Inquiry/InquiryWritePage/index.tsx
  packages/inside/src/PageContainer/Inquiry/InquiryWritePage/style.ts
  packages/outside/src/PageContainer/Admin/NewUserListPage/index.tsx
  packages/outside/src/PageContainer/Admin/NewUserListPage/style.ts
  packages/outside/src/PageContainer/Admin/UserListPage/index.tsx
  packages/outside/src/PageContainer/Admin/UserListPage/style.ts
  packages/outside/src/PageContainer/Admin/WithdrawUserListPage/index.tsx
  packages/outside/src/PageContainer/Admin/WithdrawUserListPage/style.ts
  packages/outside/src/PageContainer/Post/NoticeWritePage/index.tsx
  packages/outside/src/PageContainer/Post/NoticeWritePage/style.ts
  shared/common/src/components/PostItem/style.ts
  shared/common/src/pages/inquiry/detail/index.tsx
  shared/common/src/pages/inquiry/detail/style.ts
  shared/common/src/pages/inquiry/page/index.tsx
  shared/common/src/pages/inquiry/page/style.ts
  shared/common/src/pages/post/notice/detail/index.tsx
  shared/common/src/pages/post/notice/detail/style.ts
  shared/common/src/pages/post/notice/page/index.tsx
  shared/common/src/pages/post/notice/page/style.ts
Labels: ♻️ Refactor, 🎨 Publishing

#204 [Admin] 학교 선택 필터 refresh 상태 유지, hydration Error conflict
  package.json
  packages/outside/src/PageContainer/Club/SchoolListPage/index.tsx
  pnpm-lock.yaml
  shared/common/src/atoms/index.ts
Labels: 0️⃣ Priority: Critical, ⚡️performance, 🐞 Bug

#206 Create README.md
  README.md
Labels: 📝 Docs

#207 [Common] 게시물 페이지에 무한 스크롤 적용
  shared/api/common/src/libs/urlController.ts
  shared/common/src/hooks/index.ts
  shared/common/src/hooks/useIntersectionObserver.tsx
  shared/common/src/pages/post/notice/page/index.tsx
  shared/common/src/pages/post/page/index.tsx
  shared/common/src/pages/post/page/style.ts
  shared/types/src/api/common/PostListOptionsTypes.ts
  shared/types/src/api/common/PostListResponseTypes.ts
Labels: ✨ Feature

#208 [Common] 비밀번호 암호화
  pnpm-lock.yaml
  shared/common/.gitignore
  shared/common/package.json
  shared/common/src/assets/index.ts
  shared/common/src/components/Auth/Login/LoginForm/LoginButtons/index.tsx
  shared/common/src/components/Auth/Login/LoginForm/index.tsx
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpButtonContainer/index.tsx
  shared/common/src/utils/encryptAES.ts
  shared/common/src/utils/index.ts
Labels: ⚡️performance

#209 [Common] 공지사항 무한 스크롤 적용
  shared/common/.DS_Store
  shared/common/src/hooks/useIntersectionObserver.tsx
  shared/common/src/pages/post/notice/page/index.tsx
  shared/common/src/pages/post/page/index.tsx
  shared/common/src/pages/post/page/style.ts
Labels: ⚡️performance, ✨ Feature

#210 [Common] AES 암호화 방식 삭제
  shared/common/src/components/Auth/Login/LoginForm/index.tsx
  shared/common/src/pages/auth/signUp/SignUpPages/SignUpButtonContainer/index.tsx
  shared/common/src/utils/encryptAES.ts
  shared/common/src/utils/index.ts
Labels: ⚡️ Simple

#211 Deploy
  README.md
  pnpm-lock.yaml
  shared/api/common/src/libs/urlController.ts
  shared/common/.DS_Store
  shared/common/.gitignore
  shared/common/package.json
  shared/common/src/assets/index.ts
  shared/common/src/components/Auth/Login/LoginForm/LoginButtons/index.tsx
  shared/common/src/components/Auth/Login/LoginForm/index.tsx
  shared/common/src/hooks/index.ts
  shared/common/src/hooks/useIntersectionObserver.tsx
  shared/common/src/pages/post/notice/page/index.tsx
  shared/common/src/pages/post/page/index.tsx
  shared/common/src/pages/post/page/style.ts
  shared/types/src/api/common/PostListOptionsTypes.ts
  shared/types/src/api/common/PostListResponseTypes.ts
Labels: 🌏 Deploy

#212 [Common, Outside] 신규 가입자 수락, 거절 후 처리 변경
  packages/inside/src/PageContainer/Club/ActivityWritePage/index.tsx
  packages/outside/src/PageContainer/Admin/NewUserListPage/index.tsx
  packages/outside/src/PageContainer/Admin/UserListPage/index.tsx
  packages/outside/src/PageContainer/Admin/WithdrawUserListPage/index.tsx
  shared/api/admin/src/hooks/admin/useDeleteUserReject.ts
  shared/api/admin/src/hooks/admin/useDeleteUserWithdraw.ts
  shared/api/admin/src/hooks/admin/usePatchUserApprove.ts
  shared/api/common/src/libs/urlController.ts
  shared/common/src/components/index.ts
Labels: ⚡️performance, 🐞 Bug

#214 [Common, Inside, Outside] 사용자와 관리자 로그인 분리
  packages/inside/src/app/auth/login/page.tsx
  packages/outside/src/app/auth/login/page.tsx
  shared/api/common/src/libs/api/instance.ts
  shared/common/src/components/Auth/Login/LoginForm/LoginInput/Email/index.tsx
  shared/common/src/components/Auth/Login/LoginForm/LoginInput/Password/index.tsx
  shared/common/src/components/Auth/Login/LoginForm/index.tsx
  shared/common/src/pages/auth/login/index.tsx
  shared/common/src/pages/club/detail/index.tsx
Labels: ⚡️performance, 🐞 Bug

#216 [Common] 게시물 관련 페이지 수정하기 버튼 조건 추가
  shared/common/src/components/Auth/Login/LoginForm/index.tsx
  shared/common/src/pages/post/detail/index.tsx
Labels: 🐞 Bug

#220 [Common] 게시물 링크 관련 오류 해결 ( 관련 링크 항목, 수정 페이지 조건 )
  packages/outside/src/PageContainer/Post/NoticeWritePage/index.tsx
  shared/common/src/pages/post/detail/index.tsx
  shared/common/src/pages/post/notice/detail/index.tsx
  shared/common/src/pages/post/write/index.tsx
Labels: ⚡️ Simple
