Repository School-of-Company/Bitgouel-Frontend, pull requests merged in 2024-01, with the labels that each got.

#106 [Common] 메인 재수정
  shared/common/src/components/SchoolIntro/index.tsx
  shared/common/src/components/SchoolIntro/style.ts
  shared/common/src/components/Sequence/style.ts
  shared/common/src/pages/home/style.ts
Labels: 🎨 Publishing

#107 [Inside, Outside, Common] 동아리 페이지 퍼블리싱 (어드민, 유저)
  packages/inside/next.config.js
  packages/inside/src/PageContainer/Club/ClubPage/index.tsx
  packages/inside/src/PageContainer/Club/ClubPage/style.ts
  packages/inside/src/PageContainer/Club/index.ts
  packages/inside/src/app/main/club/page.tsx
  packages/inside/src/app/main/club/student/page.tsx
  packages/outside/src/PageContainer/Club/ClubPage/index.tsx
  packages/outside/src/PageContainer/Club/ClubPage/style.ts
  packages/outside/src/PageContainer/Club/index.ts
  packages/outside/src/PageContainer/Lecture/LecturePage/index.tsx
  packages/outside/src/app/main/club/page.tsx
  packages/outside/src/components/ClubItem/index.stories.tsx
  packages/outside/src/components/ClubItem/index.tsx
  packages/outside/src/components/ClubItem/style.ts
  packages/outside/src/components/index.ts
  shared/api/common/src/hooks/auth/index.ts
  shared/api/common/src/hooks/auth/usePatchReissue.ts
  shared/api/common/src/hooks/auth/usePostBbozzakSignUp.ts
  shared/api/common/src/hooks/auth/usePostCompanyInstructorSignUp.ts
  shared/api/common/src/hooks/auth/usePostGovernmentSignUp.ts
  shared/api/common/src/hooks/auth/usePostLogin.ts
  shared/api/common/src/hooks/auth/usePostProfessorSignUp.ts
  shared/api/common/src/hooks/auth/usePostStudentSignUp.ts
  shared/api/common/src/hooks/auth/usePostTeacherSignUp.ts
  shared/api/common/src/libs/api/instance.ts
  shared/api/inside/src/hooks/lecture/usePostApplicationLecture.ts
  shared/common/src/assets/svg/InClubArrow.tsx
  shared/common/src/assets/svg/index.ts
  shared/common/src/components/PostItem/index.tsx
  shared/common/src/components/PostItem/style.ts
  shared/common/src/pages/club/index.tsx
  shared/common/src/pages/index.ts
  shared/common/src/pages/post/index.tsx
  shared/common/src/pages/signUp/Pagination/Page3/index.tsx
Labels: 🎨 Publishing

#109 [Common, Inside, Outside] 동아리 관련 페이지 api 연결
  packages/inside/src/PageContainer/Lecture/LectureDetailPage/index.tsx
  packages/outside/src/PageContainer/Club/ClubPage/index.tsx
  packages/outside/src/PageContainer/Club/ClubPage/style.ts
  packages/outside/src/app/main/club/[clubId]/page.tsx
  packages/outside/src/app/main/club/[clubId]/student/activity/[activityId]/page.tsx
  packages/outside/src/app/main/club/[clubId]/student/activity/create/page.tsx
  packages/outside/src/app/main/club/[clubId]/student/activity/page.tsx
  packages/outside/src/app/main/club/[clubId]/student/page.tsx
  packages/outside/src/app/main/club/detail/page.tsx
  packages/outside/src/components/ClubItem/index.tsx
  packages/outside/src/modals/SchoolFilterModal/style.ts
  shared/api/common/src/libs/urlController.ts
  shared/api/inside/src/hooks/club/useGetClubDetail.ts
  shared/api/inside/src/hooks/club/useGetMyClub.ts
  shared/api/inside/src/hooks/club/useGetStudentDetail.ts
  shared/common/src/pages/club/detail/index.tsx
  shared/common/src/pages/club/detail/style.ts
  shared/common/src/pages/my/style.ts
  shared/types/src/api/client/ClubDetailResponseTypes.ts
  shared/types/src/api/client/ClubStudentResponseTypes.ts
  shared/types/src/api/client/index.ts
Labels: ✨ Feature

#110 [Common] 동아리 상세 페이지 소속 동아리 선생님 표시
  packages/outside/src/PageContainer/Lecture/LecturePage/index.tsx
  packages/outside/src/app/main/club/page.tsx
  pnpm-lock.yaml
  shared/api/admin/useGetClubList.ts
  shared/common/src/assets/svg/index.ts
  shared/common/src/constants/signUpObject.ts
  shared/common/src/modals/SelectCalendarTimeModal/index.tsx
  shared/common/src/modals/SelectCalendarTimeModal/style.ts
  shared/common/src/pages/club/detail/index.tsx
  shared/common/tsconfig.json
Labels: ⚡️ Simple

#111 [Inside] 강의 수강 신청 버튼 스타일 변경
  packages/inside/src/PageContainer/Lecture/LectureDetailPage/index.tsx
  packages/inside/src/PageContainer/Lecture/LectureDetailPage/style.ts
  shared/types/src/api/common/LectureDetailResponseTypes.ts
Labels: 🎨 Publishing

#113 [Inside, Outside] 문의 페이지 제작
  packages/inside/src/PageContainer/Club/ActivityCreatePage/index.tsx
  packages/inside/src/PageContainer/Club/ActivityModifyPage/index.tsx
  packages/inside/src/PageContainer/Inquiry/InquiryCreatePage/index.tsx
  packages/inside/src/PageContainer/Inquiry/InquiryCreatePage/style.ts
  packages/inside/src/PageContainer/Inquiry/InquiryDetailPage/index.tsx
  packages/inside/src/PageContainer/Inquiry/InquiryDetailPage/style.ts
  packages/inside/src/PageContainer/Inquiry/InquiryModifyPage/index.tsx
  packages/inside/src/PageContainer/Inquiry/InquiryModifyPage/style.ts
  packages/inside/src/PageContainer/Inquiry/InquiryPage/index.tsx
  packages/inside/src/PageContainer/Inquiry/InquiryPage/style.ts
  packages/inside/src/PageContainer/Inquiry/index.ts
  packages/inside/src/PageContainer/index.ts
  packages/inside/src/app/main/inquiry/create/page.tsx
  packages/inside/src/app/main/inquiry/detail/modify/page.tsx
  packages/inside/src/app/main/inquiry/detail/page.tsx
  packages/inside/src/app/main/inquiry/page.tsx
  packages/outside/src/PageContainer/Club/ActivityCreatePage/index.tsx
  packages/outside/src/PageContainer/Inquiry/InquiryAnswerPage/index.tsx
  packages/outside/src/PageContainer/Inquiry/InquiryAnswerPage/style.ts
  packages/outside/src/PageContainer/Inquiry/InquiryDetailPage/index.tsx
  packages/outside/src/PageContainer/Inquiry/InquiryDetailPage/style.ts
  packages/outside/src/PageContainer/Inquiry/InquiryPage/index.tsx
  packages/outside/src/PageContainer/Inquiry/InquiryPage/style.ts
  packages/outside/src/PageContainer/Inquiry/index.ts
  packages/outside/src/PageContainer/Post/NotificationCreatePage/index.tsx
  packages/outside/src/PageContainer/index.ts
  packages/outside/src/app/main/inquiry/answer/page.tsx
  packages/outside/src/app/main/inquiry/detail/page.tsx
  packages/outside/src/app/main/inquiry/page.tsx
  packages/outside/src/components/index.ts
  shared/common/src/assets/png/index.ts
  shared/common/src/assets/png/mainBg5.png
  shared/common/src/components/Header/index.tsx
  shared/common/src/components/InquiryItem/index.stories.tsx
  shared/common/src/components/InquiryItem/index.tsx
  shared/common/src/components/InquiryItem/style.ts
  shared/common/src/components/index.ts
  shared/common/src/pages/home/index.tsx
  shared/common/src/pages/post/create/index.tsx
  shared/common/src/pages/post/modify/index.tsx
  shared/common/src/pages/post/notification/modify/index.tsx
Labels: 🎨 Publishing

#114 [Inside, Outside, Common] url type 수정
  packages/inside/src/PageContainer/Club/ActivityCreatePage/style.ts
  packages/inside/src/PageContainer/Club/ActivityDetailPage/style.ts
  packages/inside/src/PageContainer/Club/ActivityListPage/style.ts
  packages/inside/src/PageContainer/Club/ActivityModifyPage/style.ts
  packages/inside/src/PageContainer/Inquiry/InquiryCreatePage/style.ts
  packages/inside/src/PageContainer/Inquiry/InquiryDetailPage/style.ts
  packages/inside/src/PageContainer/Inquiry/InquiryModifyPage/style.ts
  packages/inside/src/PageContainer/Inquiry/InquiryPage/style.ts
  packages/inside/src/PageContainer/Lecture/LectureDetailPage/style.ts
  packages/inside/src/PageContainer/Lecture/LecturePage/style.ts
  packages/inside/src/PageContainer/Post/NotificationListPage/style.ts
  packages/outside/src/PageContainer/Club/ActivityCreatePage/style.ts
  packages/outside/src/PageContainer/Club/ActivityDetailPage/style.ts
  packages/outside/src/PageContainer/Club/ActivityListPage/style.ts
  packages/outside/src/PageContainer/Club/ClubPage/style.ts
  packages/outside/src/PageContainer/Inquiry/InquiryAnswerPage/style.ts
  packages/outside/src/PageContainer/Inquiry/InquiryDetailPage/style.ts
  packages/outside/src/PageContainer/Inquiry/InquiryPage/style.ts
  packages/outside/src/PageContainer/Lecture/LectureCreatePage/style.ts
  packages/outside/src/PageContainer/Lecture/LectureDetailPage/style.ts
  packages/outside/src/PageContainer/Lecture/LecturePage/style.ts
  packages/outside/src/PageContainer/Post/NotificationCreatePage/style.ts
  packages/outside/src/PageContainer/Post/NotificationListPage/style.ts
  shared/common/src/components/ClubListContents/style.ts
  shared/common/src/components/CompanyListContents/style.ts
  shared/common/src/components/Header/style.ts
  shared/common/src/pages/club/detail/style.ts
  shared/common/src/pages/club/student/style.ts
  shared/common/src/pages/home/style.ts
  shared/common/src/pages/my/style.ts
  shared/common/src/pages/post/create/style.ts
  shared/common/src/pages/post/detail/style.ts
  shared/common/src/pages/post/modify/style.ts
  shared/common/src/pages/post/notification/detail/style.ts
  shared/common/src/pages/post/notification/modify/style.ts
  shared/common/src/pages/post/style.ts
Labels: ⚡️ Simple

#116 [Common] 비밀번호 변경 모달 퍼블리싱
  shared/common/src/components/ValueInput/index.tsx
  shared/common/src/modals/ChangePwModal/index.stories.tsx
  shared/common/src/modals/ChangePwModal/index.tsx
  shared/common/src/modals/ChangePwModal/style.ts
  shared/common/src/modals/index.ts
  shared/common/src/pages/my/index.tsx
Labels: 🎨 Publishing

#118 [Common] 헤더 toastify 설정
  shared/common/src/components/Header/index.tsx
Labels: ⚡️ Simple

#117 [Common] 비밀번호 변경 기능 구현
  packages/inside/src/modals/LectureApplyModal/index.stories.tsx
  packages/outside/src/components/ClubItem/index.stories.tsx
  pnpm-lock.yaml
  shared/api/common/src/hooks/my/index.ts
  shared/api/common/src/hooks/my/usePatchPassword.ts
  shared/api/common/src/libs/queryKeys.ts
  shared/common/src/components/InquiryItem/index.stories.tsx
  shared/common/src/components/InquiryItem/index.tsx
  shared/common/src/components/ValueInput/index.tsx
  shared/common/src/components/ValueInput/style.ts
  shared/common/src/modals/ChangePwModal/index.tsx
  shared/common/src/modals/ChangePwModal/style.ts
  shared/types/src/api/common/ChangePwPayloadTypes.ts
  shared/types/src/api/common/index.ts
Labels: ✨ Feature
